### ISSUE TITLE
flasgger

### ISSUE THREAD

**Issue by michl-in-pan** [gae-init/gae-init#1143]
Hi 
Need some help because gae-init is not working!
I tried to resolve it the whole day .-(
When I add flasgger or flask_restplus to the requirements.txt and 
from flasgger import APISpec, Schema, Swagger, fields in main.py

the following error occurs:

```
Traceback (most recent call last):
  File "/Users/michl/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/Users/michl/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/Users/michl/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 85, in LoadObject
    obj = __import__(path[0])
  File "/Users/michl/Documents/slackystoners/test/gae-init/main/main.py", line 7, in <module>
    from flasgger import APISpec, Schema, Swagger, fields
  File "lib/flasgger/__init__.py", line 7, in <module>
    from jsonschema import ValidationError  # noqa
  File "lib/jsonschema/__init__.py", line 33, in <module>
    __version__ = get_distribution(__name__).version
  File "lib/pkg_resources/__init__.py", line 481, in get_distribution
    dist = get_provider(dist)
  File "lib/pkg_resources/__init__.py", line 357, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "lib/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "lib/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
DistributionNotFound: The 'jsonschema' distribution was not found and is required by the application
```

**Comment by michl-in-pan** [comment]
My jsonschema is 2.6.0 for python 2.7

**Comment by mdxs** [comment]
Sorry, not using what you're trying to use.

As it is not a `gae-init` specific issue, I recommend this ticket to be closed.

**Comment by lipis** [comment]
Is this lib compatible with GAE in general?
