### ISSUE TITLE
Gulp `reload` task is not being terminated properly and causes an error when running again

### ISSUE THREAD

**Issue by lipis** [gae-init/gae-init#278]
How to reproduce:

1. Run `gulp` in any project
2. `Ctrl+C` to kill the process
3. Run `gulp` again

```bash
20:46:39] Starting 'run'...
[20:46:39] Starting 'watch'...
[20:46:39] Starting 'reload'...
[20:46:40] 'reload' errored after 1.06 s
[20:46:40] Error: watch ENOENT
  at errnoException (fs.js:1030:11)
  at FSWatcher.start (fs.js:1062:11)
  at Object.fs.watch (fs.js:1087:11)
  at Gaze._watchDir (/path/to/project/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:289:30)
  at /path/to/project/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:358:10
  at iterate (/path/to/project/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:52:5)
  at /path/to/project/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:61:11
  at /path/to/project/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:420:5
  at iterate (/path/to/project/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:52:5)
  at /path/to/project/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:61:11
  at /path/to/project/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:420:5
  at iterate (/path/to/project/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:52:5)
  at /path/to/project/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:61:11
  at /path/to/project/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:420:5
  at iterate (/path/to/project/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:52:5)
  at /path/to/project/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:61:11
  at /path/to/project/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:420:5
  at iterate (/path/to/project/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:52:5)
  at Object.forEachSeries (/path/to/project/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:66:3)
  at Gaze._initWatched (/path/to/project/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:354:10)
  at Gaze.add (/path/to/project/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:177:8)
  at new Gaze (/path/to/project/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:74:10)
  at gaze (/path/to/project/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:86:10)
  at Object.module.exports [as watch] (/path/to/project/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/index.js:12:17)
  at Gulp.watch (/path/to/project/node_modules/gulp/index.js:40:14)
  at Gulp.gulp.task.argv_lenght (/path/to/project/gulpfile.coffee:44:8)
  at module.exports (/path/to/project/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
  at Gulp.Orchestrator._runTask (/path/to/project/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
  at Gulp.Orchestrator._runStep (/path/to/project/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
  at Gulp.Orchestrator.start (/path/to/project/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
  at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:20
  at process._tickCallback (node.js:419:13)
  at Function.Module.runMain (module.js:499:11)
  at startup (node.js:119:16)
  at node.js:906:3

[20:46:40] Live reload server listening on: 35729
```

**Comment by gmist** [comment]
+1 I was confronted with the same issue... some kind of a race condition... Please try to replace line 69 to
``` coffee
gulp.task 'default', ['reload', 'run', 'watch']
```

**Comment by lipis** [comment]
This looks like it solves the problem.. and indeed it looks like all the processes are being killed properly..!

But since the order changed the possible message for newer version will appear further down.. we might want to make it standout somehow in the future.. but for now I think it's more important to have it working..

**Comment by lipis** [comment]
and we'll see in the future about the upgrade message..
