### ISSUE TITLE
 Unable to bind 127.0.0.1:8080

### ISSUE THREAD

**Issue by wilfriedE** [gae-init/gae-init#314]
I get this error when I do ```run.py -s``` however when I go to the main folder and run ```dev_appserver.py .```, it works properly. Any idea what the issue could be? 

```
Traceback (most recent call last):
  File "C:\Program Files (x86)\Google\google_appengine\dev_appserver.py", line 83, in <module>
    _run_file(__file__, globals())
  File "C:\Program Files (x86)\Google\google_appengine\dev_appserver.py", line 79, in _run_file
    execfile(_PATHS.script_file(script_name), globals_)
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\devappserver2\devappserver2.py", line 997, in <module>
    main()
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\devappserver2\devappserver2.py", line 990, in main
    dev_server.start(options)
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\devappserver2\devappserver2.py", line 793, in start
    self._dispatcher.start(options.api_host, apis.port, request_data)
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\devappserver2\dispatcher.py", line 182, in start
    _module.start()
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\devappserver2\module.py", line 1175, in start
    self._balanced_module.start()
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\devappserver2\wsgi_server.py", line 310, in start
    self._start_all_fixed_port(host_ports)
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\devappserver2\wsgi_server.py", line 347, in _start_all_fixed_port
    raise BindError('Unable to bind %s:%s' % self.bind_addr)
google.appengine.tools.devappserver2.wsgi_server.BindError: Unable to bind 127.0.0.1:8080
```

**Comment by lipis** [comment]
You already have something that is running on that port `:8080` so either kill the other process or run the app under a different port like this: `./run.py -sp 8912`

**Comment by wilfriedE** [comment]
:+1: resolved
