### ISSUE TITLE
AttributeError: 'module' object has no attribute 'fix_sys_path'

### ISSUE THREAD

**Issue by lipis** [gae-init/gae-init#319]
After upgrading to the latest Google Cloud SDK now I'm getting this error: 

```shell
./run.py -C

...

Installing setuptools, pip...done.
pip install -q -r requirements.txt
Traceback (most recent call last):
  File "/Users/lipis/work/lipis/gae-init/hg/init/temp/venv/bin/../lib/python2.7/site.py", line 703, in <module>
    main()
  File "/Users/lipis/work/lipis/gae-init/hg/init/temp/venv/bin/../lib/python2.7/site.py", line 683, in main
    paths_in_sys = addsitepackages(paths_in_sys)
  File "/Users/lipis/work/lipis/gae-init/hg/init/temp/venv/bin/../lib/python2.7/site.py", line 282, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/Users/lipis/work/lipis/gae-init/hg/init/temp/venv/bin/../lib/python2.7/site.py", line 204, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/Users/lipis/work/lipis/gae-init/hg/init/temp/venv/bin/../lib/python2.7/site.py", line 173, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'fix_sys_path'
```

**Comment by lipis** [comment]
It looks like the there are two `dev_appserver.py` files now in the google-cloud-sdk directory and the one with the `fix_sys_path()` is located in: `platform/google_appengine/dev_appserver.py`

By removing these lines: https://github.com/gae-init/gae-init/blob/master/run.py#L297-L300 the error goes away and seems that is working... but I'm not sure if that is needed :/ @gmist @joernhees

**Comment by gmist** [comment]
We need these lines for correct installation of pip dependencies (to prevent installation builtin packages like ```jinja2```).

**Comment by lipis** [comment]
Right.. can you come up with a fix here? Maybe we should also assume that people will install the latest gcloud or make that as a requirement?

**Comment by gmist** [comment]
Maybe somewhere like this:

rollback dev_appserver detection
``` python
+    gae_path = os.path.join(gae_path, '..', 'platform', 'google_appengine')
```

and call dev_appserver without full path
``` python 
  run_command = ' '.join(map(str, [
-    '"%s"' % os.path.join(find_gae_path(), 'dev_appserver.py'),
+  'dev_appserver.py'
```

**Comment by lipis** [comment]
I think the quotes are needed on Windows.. but can't test it now so I will leave them on.. tested it on OS X.. looks good! Will proceed with that..
