### ISSUE TITLE
When deployed to App Engine, import error for "flask" occured

### ISSUE THREAD

**Issue by nazroll** [gae-init/gae-init#328]
I'm still using version 2.1.0

I deployed the application to App Engine, and strangely enough that it has an import error.

```
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 85, in LoadObject
    obj = __import__(path[0])
  File "/base/data/home/apps/s~sparkline-auditor/dev.382801184808545852/main.py", line 3, in <module>
    import flask
ImportError: No module named flask
```

The app works in local development machine. But keeps throwing this error when I deploy.

**Comment by lipis** [comment]
before deploying you have to run the minification build..  ./run.py -m

(which will change in the near future..)

**Comment by lipis** [comment]
Is that solved?

**Comment by nazroll** [comment]
Yeap. it works. Thanks @lipis
