### ISSUE TITLE
(Flask/GAE) Unit Tests Support

### ISSUE THREAD

**Issue by TBxy** [gae-init/gae-init#346]
Are there any plans to add **unit test** support to gae-init?
Maybe something similar to [flask-engine](https://github.com/zachwill/flask-engine) (see also: [Local Unit Testing for Python]( http://code.google.com/appengine/docs/python/tools/localunittesting.html)).

Or do you have a recommended setup for tests?

*Thanks a lot for your good work.*

**Comment by joenorton** [comment]
I'm using NoseGAE (https://github.com/Trii/NoseGAE) atm, got it working
with alittle finagling of the appengine_config

Joe Norton

SoftwareByJoe.com <http://softwarebyjoe.com>
Twitter: @joenorton <http://twitter.com/joenorton>

**Comment by TBxy** [comment]
Thanks, I'll gave it a try but I still have some model test issues.

First of all I added a `try` `except` block in `appengine_config.py` (*are there better ways?*) and some simple test models plus a test directory, see a0ec37ba3275327ea4ce0a7d7741481b9bfcbd93.

The test of the simple model works (`tag_simple.py`) but the test for `tag.py`, which uses the `model.Base` class does not work and give the following error:
```
ERROR: test_init_tag (main.tests.test_model_tag.TestTag)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tobias/data/git/gae-init/main/tests/test_model_tag.py", line 14, in setUp
    import model
  File "/home/tobias/data/git/gae-init/main/model/__init__.py", line 3, in <module>
    from .base import Base
  File "/home/tobias/data/git/gae-init/main/model/base.py", line 8, in <module>
    import config
  File "/home/tobias/data/git/gae-init/main/config.py", line 29, in <module>
    CONFIG_DB = model.Config.get_master_db()
AttributeError: 'module' object has no attribute 'Config'
```
Everything works fine when I just run the app server ('gulp').
Does anyone know how to proper set this up?
Are there any plan to include this in further versions?

**Comment by TBxy** [comment]
The solution was very simple.
Before the package `model` can be imported `config` needs to be imported.
I made an example with a very small setup which works: [tbxy_test_nose](https://github.com/TBxy/gae-init/tree/tbxy_test_nose).

I still would like to see a test setup included in `gae-init`.

**Comment by lipis** [comment]
Eventually there should be some sort of unit testing, I just never had the chance to play around with it and not sure what's the latest and greatest in that area.. I'll check what you did there, but no promises as I don't want to bloat it with stuff and then removing them..

**Comment by chavz** [comment]
hello @joenorton , can i ask the steps you made to make `gae-init` work with `nose-gae` ? tried to run the latest of `nose-gae==0.5.9` against the latest of `gae-init==5.5.0`, and this is what I get:

running `nosetests --with-gae --gae-application ./main`, results to this:

```
Traceback (most recent call last):
  File "c:\python27\Lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\CCaberos\tmp\gae-init\temp\venv\Scripts\nosetests.exe\__main__.py", line 9, in <module>
  File "c:\users\ccaberos\tmp\gae-init\temp\venv\lib\site-packages\nose\core.py", line 121, in __init__
    **extra_args)
  File "c:\python27\Lib\unittest\main.py", line 94, in __init__
    self.parseArgs(argv)
  File "c:\users\ccaberos\tmp\gae-init\temp\venv\lib\site-packages\nose\core.py", line 145, in parseArgs
    self.config.configure(argv, doc=self.usage())
  File "c:\users\ccaberos\tmp\gae-init\temp\venv\lib\site-packages\nose\config.py", line 346, in configure
    self.plugins.configure(options, self)
  File "c:\users\ccaberos\tmp\gae-init\temp\venv\lib\site-packages\nose\plugins\manager.py", line 284, in configure
    cfg(options, config)
  File "c:\users\ccaberos\tmp\gae-init\temp\venv\lib\site-packages\nose\plugins\manager.py", line 99, in __call__
    return self.call(*arg, **kw)
  File "c:\users\ccaberos\tmp\gae-init\temp\venv\lib\site-packages\nose\plugins\manager.py", line 167, in simple
    result = meth(*arg, **kw)
  File "c:\users\ccaberos\tmp\gae-init\temp\venv\lib\site-packages\nosegae.py", line 85, in configure
    import appengine_config
  File "C:\Users\CCaberos\tmp\gae-init\main\appengine_config.py", line 16, in <module>
    re_ = stubs.FakeFile._skip_files.pattern.replace('|^lib/.*', '')
AttributeError: 'NoneType' object has no attribute 'pattern'
```

**Comment by chavz** [comment]
hello @TBxy, do you have gist on what you've done in  `tbxy_test_nose`, the link you've provided before in already broken. Thanks!
