### ISSUE TITLE
ImportError: No module named flask

### ISSUE THREAD

**Issue by Jogan** [gae-init/gae-init#469]
Cloned repo and changed project name in app.yaml. Was able to deploy to google app engine successfully but upon accessing an error is thrown checking the logs returns:

```
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 85, in LoadObject
    obj = __import__(path[0])
  File "/base/data/home/apps/s~<my-app-name>/1.390357638021576088/main.py", line 3, in <module>
    import flask
ImportError: No module named flask
```

**Comment by lipis** [comment]
Did you run the `npm install`? It looks like the third party libraries weren't installed..

**Comment by Jogan** [comment]
@lipis yup same issue :/

**Comment by Jogan** [comment]
@lipis ah issue resolved! I was deploying through the google app engine launcher...once I tried gulp deploy everything worked!

**Comment by lipis** [comment]
:beer: :palm_tree:
