### ISSUE TITLE
How to pass additional arguments to the dev_apperser

### ISSUE THREAD

**Issue by voscausa** [gae-init/gae-init#471]
This did not work: 

gulp run -o:localhost --smtp_host=smtp.ziggo.nl --admin_port=9000  

"C:\Program Files (x86)\JetBrains\PyCharm 5.0.3\bin\runnerw.exe" "C:\Program Files\nodejs\node.exe" C:\Users\rober\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js --color --gulpfile d:\GAEstorage\GAE-Init\phonebook\gulpfile.js run -p=8181 -o=localhost --smtp_host=smtp.ziggo.nl -s --admin_port=9000  

And this I did not understand: http://docs.gae-init.appspot.com/run/

**Comment by voscausa** [comment]
These  arguments failed: -s --appserver-args --smtp_host=smtp.ziggo.nl --admin_port=9000  

Docs :  it's possible to pass additional arg along with the --appserver-args option. So if you for example want to see debug logging output of your app in the terminal, you can run: ./run.py -s --appserver-args --log_level debug.

**Comment by lipis** [comment]
First of all that link is a bit outdated..  I will remove it eventually or replace it with the `gulp`.

The admin port is automatically set by the script.. and it's usually at 8081 or if you set a different port for the server it will be plus +1 so for example:

```
gulp -p 4444
```

will run the server at `4444` and the admin at `4445`

now if you want to pass additional arguments use the `-a=`

```
gulp -p 5555 -a='--log_level debug'
```

For more run the `gulp help` :)

**Comment by voscausa** [comment]
What is wrong here:

1) gulp additional arguments with single quotes:

```
D:\GAEstorage\GAE-Init\phonebook>gulp -o=localhost -p=8080 -a='--smtp_host smtp.ziggo.nl'
[19:52:40] Using gulpfile D:\GAEstorage\GAE-Init\phonebook\gulpfile.js
[19:52:40] Task 'smtp.ziggo.nl'' is not in your gulpfile
[19:52:40] Please check the documentation for proper gulpfile formatting
```

2) gulp additional arguments with double quotes:

```
D:\GAEstorage\GAE-Init\phonebook>gulp -o=localhost -p=8080 -a="--smtp_host smtp.ziggo.nl"
[20:05:56] Using gulpfile D:\GAEstorage\GAE-Init\phonebook\gulpfile.js

......
[20:06:02] Finished 'ext:dev' after 1.9 s
[20:06:02]  $ python run.py -s -p 8080 -o localhost --appserver-args "--smtp_host smtp.ziggo.nl"
Traceback (most recent call last):
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\dev_appserver.py", line 83, in <module>
    _run_file(__file__, globals())
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\dev_appserver.py", line 79, in _run_file
    execfile(_PATHS.script_file(script_name), globals_)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\tools\devappserver2\devappserver2.py", line 1040, in <module>
    main()
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\tools\devappserver2\devappserver2.py", line 1030, in main
    options = PARSER.parse_args()
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\lib\third_party\argparse\__init__.py", line 1703, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\lib\third_party\argparse\__init__.py", line 1735, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\lib\third_party\argparse\__init__.py", line 1941, in _parse_known_args
    start_index = consume_optional(start_index)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\lib\third_party\argparse\__init__.py", line 1881, in consume_optional
    take_action(action, args, option_string)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\lib\third_party\argparse\__init__.py", line 1809, in take_action
    action(self, namespace, argument_values, option_string)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\tools\boolean_action.py", line 63, in __call__
    setattr(namespace, self.dest, BooleanParse(values))
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\tools\boolean_action.py", line 78, in BooleanParse
    (values, ', '.join(repr_values)))
ValueError: '--smtp_host smtp.ziggo.nl' unrecognized boolean; known booleans are 'true', 'yes', '1', 'false', 'no', '0'.
```

**Comment by lipis** [comment]
@gmist any idea?

**Comment by mdxs** [comment]
Is this still an issue?

**Comment by jakedotio** [comment]
I think I stumbled across this today. 

In run.py, 
'--skip_sdk_update_check` does not have a boolean value, which it requires. So the arguments being passed with -a are being handled as the boolean value of --skip_sdk_update_check.

I just changed the line in run.py to read:
`'--skip_sdk_update_check true',`

**Comment by voscausa** [comment]
outdated
