### ISSUE TITLE
"OSError: [Errno 13] Permission denied: '/lib'" when running npm install in OS X

### ISSUE THREAD

**Issue by impiaaa** [gae-init/gae-init#543]
After following the [Requirements](http://docs.gae-init.appspot.com/requirement/) page manually, I continued to run `npm install`. It gets to `pip install -q -r requirements.txt`, then spits out this error:

```
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/site-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_set.py", line 742, in install
    **kwargs
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 831, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 1032, in move_wheel_files
    isolated=self.isolated,
  File "/usr/local/lib/python2.7/site-packages/pip/wheel.py", line 346, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/local/lib/python2.7/site-packages/pip/wheel.py", line 287, in clobber
    ensure_dir(dest)  # common for the 'include' path
  File "/usr/local/lib/python2.7/site-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/lib'
```

It continues with the install, but running `gulp` after also gives the same error, as well as a `ImportError: No module named flask` when it tries to start the server. I'm new to this and just wanted to get something started. It could be something I set up wrong with the environment, but all of the commands on the requirements page run fine. Surely `npm install` shouldn't install things globally? I'm sorry if this is the wrong place to post. I couldn't find any support or forum-type places on the homepage.

**Comment by lipis** [comment]
You might messed something with the rights in the past.. Maybe you installed some of the npm packages using sudo when you shouldn't or something similar.

Are you getting the same error with  'gulp pip'?

**Comment by impiaaa** [comment]
Yes, the same error happens with `gulp pip`. Although, I tried starting the project from scratch, and got a slightly different error this time:
```
> gae-init@ install <project>
> gulp init

(node:52861) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[21:38:36] Using gulpfile <project>/gulpfile.js
[21:38:36] Starting 'init'...
[21:38:36] Starting 'pip'...
[21:38:37]  $ python run.py -d
New python executable in <project>/temp/venv/bin/python2.7
Also creating executable in <project>/temp/venv/bin/python
Please make sure you remove any previous custom paths from your <home>/.pydistutils.cfg file.
Installing setuptools, pip, wheel...
  Complete output from command "<project>...p/venv/bin/python2.7" - setuptools pip wheel:
  Collecting setuptools
  Downloading setuptools-24.0.1-py2.py3-none-any.whl (441kB)
Collecting pip
Collecting wheel
Installing collected packages: setuptools, pip, wheel
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/virtualenv_support/pip-8.1.2-py2.py3-none-any.whl/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/site-packages/virtualenv_support/pip-8.1.2-py2.py3-none-any.whl/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python2.7/site-packages/virtualenv_support/pip-8.1.2-py2.py3-none-any.whl/pip/req/req_set.py", line 742, in install
    **kwargs
  File "/usr/local/lib/python2.7/site-packages/virtualenv_support/pip-8.1.2-py2.py3-none-any.whl/pip/req/req_install.py", line 831, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/local/lib/python2.7/site-packages/virtualenv_support/pip-8.1.2-py2.py3-none-any.whl/pip/req/req_install.py", line 1032, in move_wheel_files
    isolated=self.isolated,
  File "/usr/local/lib/python2.7/site-packages/virtualenv_support/pip-8.1.2-py2.py3-none-any.whl/pip/wheel.py", line 346, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/local/lib/python2.7/site-packages/virtualenv_support/pip-8.1.2-py2.py3-none-any.whl/pip/wheel.py", line 287, in clobber
    ensure_dir(dest)  # common for the 'include' path
  File "/usr/local/lib/python2.7/site-packages/virtualenv_support/pip-8.1.2-py2.py3-none-any.whl/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "<project>/temp/venv/bin/../lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "<project>/temp/venv/bin/../lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "<project>/temp/venv/bin/../lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/lib'
```
(that's just the first bit, it only gets worse from there.)
The initial [requirements](http://docs.gae-init.appspot.com/requirement/) I did install with sudo, but only because those should be installed globally.

**Comment by lipis** [comment]
Did you do all of them with sudo?! Because `node/npm` related are not suppose to be with sudo.. obviously you have some permission issues and I've seen it quite a few times.. my guess is that it might run if you do `sudo gulp`, but that's not a solution..

**Comment by impiaaa** [comment]
Finally got around to trying to fix the issue. For some reason my ~/.pydistutils.cfg contained
`[install]
prefix=
`, which messed up the virtualenv creation.

To find it I ended up adding debug code to run.py to see what it was doing, removed the "temp" folder to force it to re-create the venv, ran the virtualenv command myself to see what was wrong, which helpfully told me "Please make sure you remove any previous custom paths from your ~/.pydistutils.cfg file".

**Comment by lipis** [comment]
I'm glad you solved it and thank you for following up :) No matter how much I love Python.. these things I hate about it :) there is always one little thing that you might forget :)
