### ISSUE TITLE
Cannot install on windows

### ISSUE THREAD

**Issue by phivo** [gae-init/gae-init#549]
Followed all prerequisites, `npm install` was successful, but running `gulp` was not.
It throws an error on module.js:422, saying that cannot find module `lodash.keys`.

Please help. Error code below

```
Error: Cannot find module 'lodash.keys'
  at Function.Module._resolveFilename (module.js:440:15)
  at Function.Module._load (module.js:388:25)
  at Module.require (module.js:468:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (C:\Users\xxxxxx\coding\gae-init\node_modules\lodash.template\index.js:14:12)
  at Module._compile (module.js:541:32)
  at Object.Module._extensions..js (module.js:550:10)
  at Module.load (C:\Users\xxxxxx\coding\gae-init\node_modules\coffee-script\lib\coffee-script\register.js:45:36)
  at tryModuleLoad (module.js:417:12)
  at Function.Module._load (module.js:409:3)
  at Module.require (module.js:468:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (C:\Users\xxxxxx\coding\gae-init\node_modules\gulp-util\lib\template.js:1:78)
  at Module._compile (module.js:541:32)
  at Object.Module._extensions..js (module.js:550:10)
  at Module.load (C:\Users\xxxxxx\coding\gae-init\node_modules\coffee-script\lib\coffee-script\register.js:45:36)
  at tryModuleLoad (module.js:417:12)
  at Function.Module._load (module.js:409:3)
  at Module.require (module.js:468:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (C:\Users\xxxxxx\coding\gae-init\node_modules\gulp-util\index.js:7:13)
  at Module._compile (module.js:541:32)
  at Object.Module._extensions..js (module.js:550:10)
  at Module.load (C:\Users\xxxxxx\coding\gae-init\node_modules\coffee-script\lib\coffee-script\register.js:45:36)
  at tryModuleLoad (module.js:417:12)
  at Function.Module._load (module.js:409:3)
  at Module.require (module.js:468:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (C:\Users\xxxxxx\coding\gae-init\node_modules\gulp\index.js:5:13)
  at Module._compile (module.js:541:32)
  at Object.Module._extensions..js (module.js:550:10)
  at Module.load (C:\Users\xxxxxx\coding\gae-init\node_modules\coffee-script\lib\coffee-script\register.js:45:36)
  at tryModuleLoad (module.js:417:12)
  at Function.Module._load (module.js:409:3)
  at Module.require (module.js:468:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (C:\Users\xxxxxx\coding\gae-init\gulpfile.coffee:1:29)
  at Object.<anonymous> (C:\Users\xxxxxx\coding\gae-init\gulpfile.coffee:1:1)
  at Module._compile (module.js:541:32)
  at Object.loadFile (C:\Users\xxxxxx\coding\gae-init\node_modules\coffee-script\lib\coffee-script\register.js:16:19)
  at Module.load (C:\Users\xxxxxx\coding\gae-init\node_modules\coffee-script\lib\coffee-script\register.js:45:36)
  at tryModuleLoad (module.js:417:12)
  at Function.Module._load (module.js:409:3)
  at Module.require (module.js:468:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (C:\Users\xxxxxx\coding\gae-init\gulpfile.js:2:1)
  at Module._compile (module.js:541:32)
  at Object.Module._extensions..js (module.js:550:10)
  at Module.load (module.js:458:32)
  at tryModuleLoad (module.js:417:12)
  at Function.Module._load (module.js:409:3)
  at Module.require (module.js:468:17)
  at require (internal/module.js:20:19)
  at Liftoff.handleArguments (C:\Users\xxxxxx\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:116:3)
  at Liftoff.<anonymous> (C:\Users\xxxxxx\AppData\Roaming\npm\node_modules\gulp\node_modules\liftoff\index.js:198:16)
  at module.exports (C:\Users\xxxxxx\AppData\Roaming\npm\node_modules\gulp\node_modules\flagged-respawn\index.js:17:3)
  at Liftoff.<anonymous> (C:\Users\xxxxxx\AppData\Roaming\npm\node_modules\gulp\node_modules\liftoff\index.js:190:9)
  at C:\Users\xxxxxx\AppData\Roaming\npm\node_modules\gulp\node_modules\liftoff\index.js:164:9
  at C:\Users\xxxxxx\AppData\Roaming\npm\node_modules\gulp\node_modules\v8flags\index.js:108:14
  at C:\Users\xxxxxx\AppData\Roaming\npm\node_modules\gulp\node_modules\v8flags\index.js:36:12
  at C:\Users\xxxxxx\AppData\Roaming\npm\node_modules\gulp\node_modules\v8flags\index.js:47:7
  at _combinedTickCallback (internal/process/next_tick.js:67:7)
  at process._tickCallback (internal/process/next_tick.js:98:9)
  at Function.Module.runMain (module.js:577:11)
  at startup (node.js:160:18)
  at node.js:449:3

```

**Comment by lipis** [comment]
What are the Node and npm versions installed on your machine... get the [latest one](https://nodejs.org/en/) (6.5.0) and try again.

**Comment by lipis** [comment]
I'll reopen it if you still have issues after installing the latest Node
