### ISSUE TITLE
High CPU consumption when running gulp locally

### ISSUE THREAD

**Issue by ventice** [gae-init/gae-init#580]
**Platform:** Windows
**Steps to reproduce:**
1. Run local server by typing `gulp`
2. Open task manager and find `node.exe` process

**Result:**
node.exe consumes about 100% of CPU
**Expected result:**
node.exe consumes less than 25% of CPU

**Side notes:**
The issue is caused by gulp.watch for livereload. As reported in [Isse#634 of gulp.watch](https://github.com/gulpjs/gulp/issues/634), this can be mitigated by increasing watch interval.

**Comment by gmist** [comment]
You can use ```gulp-watch``` instead ```gulp.watch```:
1. [npm install gulp-watch --save-dev](https://github.com/gae-init/gae-init/pull/550/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R34)
2. [replace ```watch``` by ```gulp.watch```](https://github.com/gae-init/gae-init/pull/550/files#diff-724f8714ebe98bf7b20b1fb62e8ca522R20)

**Comment by ventice** [comment]
I already fixed it by increasing polling interval as recommended in the cited issue. Creating pull request.

**Comment by lipis** [comment]
Hey @ventice I tried the gulp-watch as recommended from @gmist so there's the PR #583 can you check if the CPU still high with it? It should be better now...

**Comment by ventice** [comment]
Ok, will check tomorrow and keep you posted.

**Comment by ventice** [comment]
Took `package.json` and `watch.coffee` from given PR and started gulp. Got a warning and looped watching of `ext`:

[15:22:34] Starting 'ext:dev'...
(node) warning: possible EventEmitter memory leak detected. 11 task_stop listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
  at Gulp.addListener (events.js:239:17)
  at C:\Users\venticello\GoogleApps\opttorg-api\default\node_modules\gulp-sequen
ce\index.js:58:12
  at apply (C:\Users\venticello\GoogleApps\opttorg-api\default\node_modules\gulp-sequence\node_modules\thunks\thunks.js:338:38)
  at tryRun (C:\Users\venticello\GoogleApps\opttorg-api\default\node_modules\gulp-sequence\node_modules\thunks\thunks.js:217:19)
  at runThunk (C:\Users\venticello\GoogleApps\opttorg-api\default\node_modules\gulp-sequence\node_modules\thunks\thunks.js:210:15)
  at C:\Users\venticello\GoogleApps\opttorg-api\default\node_modules\gulp-sequence\node_modules\thunks\thunks.js:302:49
  at apply (C:\Users\venticello\GoogleApps\opttorg-api\default\node_modules\gulp-sequence\node_modules\thunks\thunks.js:338:38)
  at tryRun (C:\Users\venticello\GoogleApps\opttorg-api\default\node_modules\gulp-sequence\node_modules\thunks\thunks.js:217:19)
  at runThunk (C:\Users\venticello\GoogleApps\opttorg-api\default\node_modules\gulp-sequence\node_modules\thunks\thunks.js:210:15)
  at continuation (C:\Users\venticello\GoogleApps\opttorg-api\default\node_modules\gulp-sequence\node_modules\thunks\thunks.js:168:54)
  at child (C:\Users\venticello\GoogleApps\opttorg-api\default\node_modules\gulp-sequence\node_modules\thunks\thunks.js:160:24)
  at C:\Users\venticello\GoogleApps\opttorg-api\default\node_modules\gulp-sequence\node_modules\thunks\thunks.js:152:14
  at C:\Users\venticello\GoogleApps\opttorg-api\default\gulp\tasks\watch.coffee:29:5
  at write (C:\Users\venticello\GoogleApps\opttorg-api\default\node_modules\gulp-watch\index.js:146:3)
  at C:\Users\venticello\GoogleApps\opttorg-api\default\node_modules\gulp-watch\index.js:129:5

(node) warning: possible EventEmitter memory leak detected. 11 task_not_found listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
  at Gulp.addListener (events.js:239:17)
  at C:\Users\venticello\GoogleApps\opttorg-api\default\node_modules\gulp-sequence\index.js:59:12
  at apply (C:\Users\venticello\GoogleApps\opttorg-api\default\node_modules\gulp-sequence\node_modules\thunks\thunks.js:338:38)
  at tryRun (C:\Users\venticello\GoogleApps\opttorg-api\default\node_modules\gulp-sequence\node_modules\thunks\thunks.js:217:19)
  at runThunk (C:\Users\venticello\GoogleApps\opttorg-api\default\node_modules\gulp-sequence\node_modules\thunks\thunks.js:210:15)
  at C:\Users\venticello\GoogleApps\opttorg-api\default\node_modules\gulp-sequence\node_modules\thunks\thunks.js:302:49
  at apply (C:\Users\venticello\GoogleApps\opttorg-api\default\node_modules\gulp-sequence\node_modules\thunks\thunks.js:338:38)
  at tryRun (C:\Users\venticello\GoogleApps\opttorg-api\default\node_modules\gulp-sequence\node_modules\thunks\thunks.js:217:19)
  at runThunk (C:\Users\venticello\GoogleApps\opttorg-api\default\node_modules\gulp-sequence\node_modules\thunks\thunks.js:210:15)
  at continuation (C:\Users\venticello\GoogleApps\opttorg-api\default\node_modules\gulp-sequence\node_modules\thunks\thunks.js:168:54)
  at child (C:\Users\venticello\GoogleApps\opttorg-api\default\node_modules\gulp-sequence\node_modules\thunks\thunks.js:160:24)
  at C:\Users\venticello\GoogleApps\opttorg-api\default\node_modules\gulp-sequence\node_modules\thunks\thunks.js:152:14
  at C:\Users\venticello\GoogleApps\opttorg-api\default\gulp\tasks\watch.coffee:29:5
  at write (C:\Users\venticello\GoogleApps\opttorg-api\default\node_modules\gulp-watch\index.js:146:3)
  at C:\Users\venticello\GoogleApps\opttorg-api\default\node_modules\gulp-watch\index.js:129:5

(node) warning: possible EventEmitter memory leak detected. 11 task_err listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
  at Gulp.addListener (events.js:239:17)
  at C:\Users\venticello\GoogleApps\opttorg-api\default\node_modules\gulp-sequence\index.js:61:12
  at apply (C:\Users\venticello\GoogleApps\opttorg-api\default\node_modules\gulp-sequence\node_modules\thunks\thunks.js:338:38)
  at tryRun (C:\Users\venticello\GoogleApps\opttorg-api\default\node_modules\gulp-sequence\node_modules\thunks\thunks.js:217:19)
  at runThunk (C:\Users\venticello\GoogleApps\opttorg-api\default\node_modules\gulp-sequence\node_modules\thunks\thunks.js:210:15)
  at C:\Users\venticello\GoogleApps\opttorg-api\default\node_modules\gulp-sequence\node_modules\thunks\thunks.js:302:49
  at apply (C:\Users\venticello\GoogleApps\opttorg-api\default\node_modules\gulp-sequence\node_modules\thunks\thunks.js:338:38)
  at tryRun (C:\Users\venticello\GoogleApps\opttorg-api\default\node_modules\gulp-sequence\node_modules\thunks\thunks.js:217:19)
  at runThunk (C:\Users\venticello\GoogleApps\opttorg-api\default\node_modules\gulp-sequence\node_modules\thunks\thunks.js:210:15)
  at continuation (C:\Users\venticello\GoogleApps\opttorg-api\default\node_modules\gulp-sequence\node_modules\thunks\thunks.js:168:54)
  at child (C:\Users\venticello\GoogleApps\opttorg-api\default\node_modules\gulp-sequence\node_modules\thunks\thunks.js:160:24)
  at C:\Users\venticello\GoogleApps\opttorg-api\default\node_modules\gulp-sequence\node_modules\thunks\thunks.js:152:14
  at C:\Users\venticello\GoogleApps\opttorg-api\default\gulp\tasks\watch.coffee:29:5
  at write (C:\Users\venticello\GoogleApps\opttorg-api\default\node_modules\gulp-watch\index.js:146:3)
  at C:\Users\venticello\GoogleApps\opttorg-api\default\node_modules\gulp-watch\index.js:129:5

(node) warning: possible EventEmitter memory leak detected. 11 task_recursion listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
  at Gulp.addListener (events.js:239:17)
  at C:\Users\venticello\GoogleApps\opttorg-api\default\node_modules\gulp-sequence\index.js:60:12
  at apply (C:\Users\venticello\GoogleApps\opttorg-api\default\node_modules\gulp-sequence\node_modules\thunks\thunks.js:338:38)
  at tryRun (C:\Users\venticello\GoogleApps\opttorg-api\default\node_modules\gulp-sequence\node_modules\thunks\thunks.js:217:19)
  at runThunk (C:\Users\venticello\GoogleApps\opttorg-api\default\node_modules\gulp-sequence\node_modules\thunks\thunks.js:210:15)
  at C:\Users\venticello\GoogleApps\opttorg-api\default\node_modules\gulp-sequence\node_modules\thunks\thunks.js:302:49
  at apply (C:\Users\venticello\GoogleApps\opttorg-api\default\node_modules\gulp-sequence\node_modules\thunks\thunks.js:338:38)
  at tryRun (C:\Users\venticello\GoogleApps\opttorg-api\default\node_modules\gulp-sequence\node_modules\thunks\thunks.js:217:19)
  at runThunk (C:\Users\venticello\GoogleApps\opttorg-api\default\node_modules\gulp-sequence\node_modules\thunks\thunks.js:210:15)
  at continuation (C:\Users\venticello\GoogleApps\opttorg-api\default\node_modules\gulp-sequence\node_modules\thunks\thunks.js:168:54)
  at child (C:\Users\venticello\GoogleApps\opttorg-api\default\node_modules\gulp-sequence\node_modules\thunks\thunks.js:160:24)
  at C:\Users\venticello\GoogleApps\opttorg-api\default\node_modules\gulp-sequence\node_modules\thunks\thunks.js:152:14
  at C:\Users\venticello\GoogleApps\opttorg-api\default\gulp\tasks\watch.coffee:29:5
  at write (C:\Users\venticello\GoogleApps\opttorg-api\default\node_modules\gulp-watch\index.js:146:3)
  at C:\Users\venticello\GoogleApps\opttorg-api\default\node_modules\gulp-watch\index.js:129:5

[15:22:36] Finished 'ext:dev' after 1.62 s
[15:22:36] Starting 'ext:dev'...
[15:22:36] C:\Users\venticello\GoogleApps\opttorg-api\default\main\static\dev\script\ext.js reloaded.
[15:22:37] Finished 'ext:dev' after 1.13 s
[15:22:37] C:\Users\venticello\GoogleApps\opttorg-api\default\main\static\dev\script\ext.js reloaded.
[15:22:37] Starting 'ext:dev'...
[15:22:37] C:\Users\venticello\GoogleApps\opttorg-api\default\main\static\dev\script\ext.js reloaded.
[15:22:38] Finished 'ext:dev' after 963 ms
[15:22:38] Starting 'ext:dev'...
[15:22:38] C:\Users\venticello\GoogleApps\opttorg-api\default\main\static\dev\script\ext.js reloaded.
[15:22:40] Finished 'ext:dev' after 1.42 s
[15:22:40] Starting 'ext:dev'...
[15:22:40] C:\Users\venticello\GoogleApps\opttorg-api\default\main\static\dev\script\ext.js reloaded.
[15:22:41] Finished 'ext:dev' after 1.24 s
[15:22:41] Starting 'ext:dev'...
[15:22:41] C:\Users\venticello\GoogleApps\opttorg-api\default\main\static\dev\script\ext.js reloaded.
[15:22:42] Finished 'ext:dev' after 1.15 s
[15:22:42] Starting 'ext:dev'...
[15:22:42] C:\Users\venticello\GoogleApps\opttorg-api\default\main\static\dev\script\ext.js reloaded.
[15:22:43] Finished 'ext:dev' after 1.15 s
[15:22:43] Starting 'ext:dev'...
[15:22:43] C:\Users\venticello\GoogleApps\opttorg-api\default\main\static\dev\script\ext.js reloaded.
[15:22:45] Finished 'ext:dev' after 1.3 s
[15:22:45] C:\Users\venticello\GoogleApps\opttorg-api\default\main\static\dev\script\ext.js reloaded.

**Comment by lipis** [comment]
Lets continue on #583

**Comment by lipis** [comment]
I guess this should be solved now..
