### ISSUE TITLE
UnitTest with NoseGae/PytestGae: Unable to load stubs.FakeFile._skip_files.pattern.replace('|^lib/.*', '') when running test

### ISSUE THREAD

**Issue by chavz** [gae-init/gae-init#594]
I just tried to run nosetest on a fresh gae-init installation, and this is what I get.

when running..
```
13:54 $ nosetests --with-gae --gae-application ./main/ --gae-lib-root /c/Users/CCaberos/AppData/Local/Google/Cloud/AppEngine
```

this is what I get..
```
Traceback (most recent call last):
  File "c:\python27\Lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\CCaberos\tmp\gae-init-nose\temp\venv\Scripts\nosetests.exe\__main__.py", line 9, in <module>
  File "c:\users\ccaberos\tmp\gae-init-nose\temp\venv\lib\site-packages\nose\core.py", line 121, in __init__
    **extra_args)
  File "c:\python27\Lib\unittest\main.py", line 94, in __init__
    self.parseArgs(argv)
  File "c:\users\ccaberos\tmp\gae-init-nose\temp\venv\lib\site-packages\nose\core.py", line 145, in parseArgs
    self.config.configure(argv, doc=self.usage())
  File "c:\users\ccaberos\tmp\gae-init-nose\temp\venv\lib\site-packages\nose\config.py", line 346, in configure
    self.plugins.configure(options, self)
  File "c:\users\ccaberos\tmp\gae-init-nose\temp\venv\lib\site-packages\nose\plugins\manager.py", line 284, in configure
    cfg(options, config)
  File "c:\users\ccaberos\tmp\gae-init-nose\temp\venv\lib\site-packages\nose\plugins\manager.py", line 99, in __call__
    return self.call(*arg, **kw)
  File "c:\users\ccaberos\tmp\gae-init-nose\temp\venv\lib\site-packages\nose\plugins\manager.py", line 167, in simple
    result = meth(*arg, **kw)
  File "c:\users\ccaberos\tmp\gae-init-nose\temp\venv\lib\site-packages\nosegae.py", line 85, in configure
    import appengine_config
  File "C:\Users\CCaberos\tmp\gae-init-nose\main\appengine_config.py", line 16, in <module>
    re_ = stubs.FakeFile._skip_files.pattern.replace('|^lib/.*', '')
AttributeError: 'NoneType' object has no attribute 'pattern'
```

NoseGae#0.5.9
gae-init#5.5.0

might be related to issue #346, already asked the involved people there for help, but just in case some other people has encountered it and may be able to help.

**Comment by chavz** [comment]
okay tried to do the same tests with [`pytest_gae`](https://pypi.python.org/pypi/pytest_gae) but i get the same results:

```
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
..\..\AppData\Local\Google\Cloud\AppEngine\google\appengine\ext\ndb\model.py:3451: in _put
    return self._put_async(**ctx_options).get_result()
..\..\AppData\Local\Google\Cloud\AppEngine\google\appengine\ext\ndb\model.py:3465: in _put_async
    self._key = Key(self._get_kind(), None)
..\..\AppData\Local\Google\Cloud\AppEngine\google\appengine\ext\ndb\key.py:235: in __new__
    self.__namespace) = self._parse_from_args(**kwargs)
..\..\AppData\Local\Google\Cloud\AppEngine\google\appengine\ext\ndb\key.py:300: in _parse_from_args
    namespace = _DefaultNamespace()
..\..\AppData\Local\Google\Cloud\AppEngine\google\appengine\ext\ndb\key.py:853: in _DefaultNamespace
    return namespace_manager.get_namespace()
..\..\AppData\Local\Google\Cloud\AppEngine\google\appengine\api\namespace_manager\namespace_manager.py:88: in get_namespace
    name = _config.default_namespace_for_request()
..\..\AppData\Local\Google\Cloud\AppEngine\google\appengine\api\lib_config.py:354: in __getattr__
    self._update_configs()
..\..\AppData\Local\Google\Cloud\AppEngine\google\appengine\api\lib_config.py:290: in _update_configs
    self._registry.initialize()
..\..\AppData\Local\Google\Cloud\AppEngine\google\appengine\api\lib_config.py:165: in initialize
    import_func(self._modname)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    import os
    import sys

    if os.environ.get('SERVER_SOFTWARE', '').startswith('Google App Engine'):
      sys.path.insert(0, 'lib.zip')
    else:
      if os.name == 'nt':
        os.name = None
        sys.platform = ''

      import re
      from google.appengine.tools.devappserver2.python import stubs

>     re_ = stubs.FakeFile._skip_files.pattern.replace('|^lib/.*', '')
E     AttributeError: 'NoneType' object has no attribute 'pattern'

main\appengine_config.py:16: AttributeError

```

by the way I'm just using the sample tests provided by google in [localunittesting](https://cloud.google.com/appengine/docs/python/tools/localunittesting), i'm running them directly from nosetests/pytest instead of from the `runner.py`

**Comment by lipis** [comment]
I never played with those.. :( Also not much time these days to play around with it..

**Comment by gmist** [comment]
``` python
  if stubs.FakeFile._skip_files:
    re_ = stubs.FakeFile._skip_files.pattern.replace('|^lib/.*', '')
    re_ = re.compile(re_)
    stubs.FakeFile._skip_files = re_
  sys.path.insert(0, 'lib')
```

**Comment by lipis** [comment]
Did you manage to make it run @chavz?

**Comment by chavz** [comment]
yup! sorry I wasn't able to follow up on this sooner, I decided to defer the unit testing since i'm encountering a lot of issues with it, but yes, with the snippet that @gmist provided, I was able to run the sample tests that google provided in their [local unit testing docs](https://cloud.google.com/appengine/docs/python/tools/localunittesting), both with `nose-gae` & `pytest-gae` _(although I have to do a little bit more fiddling in pytest-gae to make it work, see [pytest-gae#6](https://bitbucket.org/petraszd/pytest_gae/issues/6), and in tandem with [pytest-beds](https://pypi.python.org/pypi/pytest-beds))_.

There's some caveats though, with `pytest-gae` you have to do the imports inside the test function, e.g.

```python
# this wont work

from main.model import User

def test_sample_one(ndb):  # ndb is fixture from pytest-beds
    u = User(username='johndoe', email='johndoe@company.com')
    assert u.username == 'johndoe'
    asser u.email == 'johndoe@company.com'

```

```python
# but this will do

def test_sample_one(ndb):  # ndb is fixture from pytest-beds
    from main.model import User

    u = User(username='johndoe', email='johndoe@company.com')
    assert u.username == 'johndoe'
    asser u.email == 'johndoe@company.com'

```

and I can't seem to be able to import the `app` from the `main` module _(I'm planning to use `webtest` for the functional tests, as described in [Handler Testing For Python](https://cloud.google.com/appengine/docs/python/tools/handlertesting) )_

```python
# tests/conftest.py

import pytest
import webtest as wb

import main


@pytest.fixture(scope='session')
def app(request):
    """Session-wide test `Flask` application."""
    app = main.app
    # Establish an application context before running the tests.
    ctx = app.app_context()
    ctx.push()

    def teardown():
        ctx.pop()

    request.addfinalizer(teardown)

    return app


@pytest.fixture(scope='session')
def webtest(app, request):
    webtest = wb.TestApp(app)

    def teardown():
        pass

    request.addfinalizer(teardown)

    return webtest

```

running pytest with the above `conftest.py` results to an `AttributeError`, see below:

```python
    @pytest.fixture(scope='session')
    def app(request):
        """Session-wide test `Flask` application."""
>       app = main.app
E       AttributeError: 'module' object has no attribute 'app'

tests/conftest.py:10: AttributeError
```

neither with  `from main import app`. And replacing `import main` with  `from main import main as mn` and then replacing `app = main.app` with `app = mn.app`, produces a different kind of error, see below:

```
Traceback (most recent call last):
  File "/home/jorge/projects/gae-init/temp/venv/local/lib/python2.7/site-packages/_pytest/config.py", line 337, in _importconftest
    mod = conftestpath.pyimport()
  File "/home/jorge/projects/gae-init/temp/venv/local/lib/python2.7/site-packages/py/_path/local.py", line 650, in pyimport
    __import__(modname)
  File "/home/jorge/projects/gae-init/temp/venv/local/lib/python2.7/site-packages/_pytest/assertion/rewrite.py", line 207, in load_module
    py.builtin.exec_(co, mod.__dict__)
  File "/home/jorge/projects/gae-init/temp/venv/local/lib/python2.7/site-packages/py/_builtin.py", line 221, in exec_
    exec2(obj, globals, locals)
  File "<string>", line 7, in exec2
  File "/home/jorge/projects/gae-init/tests/conftest.py", line 4, in <module>
    from main.main import app as ap
  File "/home/jorge/projects/gae-init/main/main.py", line 19, in <module>
    import auth
  File "/home/jorge/projects/gae-init/main/auth/__init__.py", line 3, in <module>
    from .auth import *
  File "/home/jorge/projects/gae-init/main/auth/auth.py", line 16, in <module>
    import cache
ImportError: No module named cache
ERROR: could not load /home/jorge/projects/gae-init/tests/conftest.py
```

In the end, I'm still trying to wrap my head around all this import issues/rules and stuff that app engine introduces, specially those, stubs and configs, since most of the time, those are where the problems occur.

**Comment by topless** [comment]
I stumbled on the same issue, even with @gmist suggestion, it cannot fails on the previous line `from google.appengine.tools.devappserver2.python import stubs` I followed the paths and tools are not there, I am working on a clean installation with the beta gcloud command if it matters.

**Comment by lipis** [comment]
I'm closing this one for now.. if there are still issues.. please report..
