### ISSUE TITLE
Error import  lib/google modules

### ISSUE THREAD

**Issue by ofl** [gae-init/gae-init#603]
Hi.

I'd like to add Firebase authentication.

https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/appengine/standard/firebase/firenotes

I was able to run the above sample, but in gae-init I can not import google's module correctly.

```
blinker==1.4
flask-login==0.4.0
flask-oauthlib==0.9.3
flask-restful==0.3.5
flask-wtf==0.13.1
flask==0.11.1
pyjwt==1.4.2
unidecode==0.4.19
webargs==1.4.0

google-auth==0.5.0
requests==2.12.4
oauth2client==4.0.0
python-firebase-gae==1.0.1
```

```
lib/
  ├ firebase/
  ├ google/
        ├ auth/
        └ oauth2/
```

```python
from firebase import firebase # OK

import google

print(google) # <module 'google' from '/Users/sim/google-cloud-sdk/platform/google_appengine/google/__init__.pyc'>
```

```
import google.oauth2.id_token

Traceback (most recent call last):
  File "/Users/sim/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/Users/sim/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/Users/sim/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 85, in LoadObject
    obj = __import__(path[0])
  File "/Users/sim/Projects/python/genbun-srv/main/main.py", line 28, in <module>
    import api.v1
  File "/Users/sim/Projects/python/genbun-srv/main/api/v1/__init__.py", line 6, in <module>
    from .profile import *
  File "/Users/sim/Projects/python/genbun-srv/main/api/v1/profile.py", line 20, in <module>
    import google.oauth2.id_token
ImportError: No module named oauth2.id_token
```

```
from google.oauth2 import id_token

Traceback (most recent call last):
  File "/Users/sim/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/Users/sim/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/Users/sim/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 85, in LoadObject
    obj = __import__(path[0])
  File "/Users/sim/Projects/python/genbun-srv/main/main.py", line 28, in <module>
    import api.v1
  File "/Users/sim/Projects/python/genbun-srv/main/api/v1/__init__.py", line 6, in <module>
    from .profile import *
  File "/Users/sim/Projects/python/genbun-srv/main/api/v1/profile.py", line 22, in <module>
    from google import oauth2
ImportError: cannot import name oauth2

```

```
pip list

aniso8601 (1.2.0)
antlr-python-runtime (3.1.1)
blinker (1.4)
click (6.6)
Flask (0.11.1)
Flask-Login (0.4.0)
Flask-OAuthlib (0.9.3)
Flask-RESTful (0.3.5)
Flask-WTF (0.13.1)
google-auth (0.5.0)
httplib2 (0.9.2)
itsdangerous (0.24)
Jinja2 (2.6)
MarkupSafe (0.15)
marshmallow (2.10.5)
oauth2client (4.0.0)
oauthlib (2.0.1)
pip (9.0.1)
PyAMF (0.6.1)
pyasn1 (0.1.9)
pyasn1-modules (0.0.8)
PyJWT (1.4.2)
python-dateutil (2.6.0)
python-firebase-gae (1.0.1)
pytz (2016.10)
requests (2.12.4)
requests-oauthlib (0.7.0)
requests-toolbelt (0.7.0)
rsa (3.4.2)
setuptools (32.3.0)
six (1.10.0)
Unidecode (0.4.19)
webapp2 (2.5.2)
webargs (1.4.0)
WebOb (1.2.3)
Werkzeug (0.11.11)
wheel (0.29.0)
WTForms (2.1)
```

Thanks.

**Comment by gmist** [comment]
It looks like a conflict between ```lib/google``` package and global ```google``` package, when the global package shadows ```lib/google```. Try to rename ```lib\google``` to ```lib\ggl```:
``` python
from ggl.oauth2 import id_token
```

**Comment by ofl** [comment]
Thanks for the advice.
Certainly I can import the module by renaming the directory as "lib/ggl".
However, it seems that it is necessary to rewrite all "google.auth.xxx" in the library under "lib/ggl".

```
Traceback (most recent call last):
  File "/Users/sim/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/Users/sim/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/Users/sim/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 85, in LoadObject
    obj = __import__(path[0])
  File "/Users/sim/Projects/python/genbun-srv/main/main.py", line 28, in <module>
    import api.v1
  File "/Users/sim/Projects/python/genbun-srv/main/api/v1/__init__.py", line 6, in <module>
    from .profile import *
  File "/Users/sim/Projects/python/genbun-srv/main/api/v1/profile.py", line 15, in <module>
    import ggl.auth.transport.requests as transport_request
  File "lib/ggl/auth/__init__.py", line 19, in <module>
    from google.auth._default import default
ImportError: No module named auth._default
```

**Comment by ofl** [comment]
I was able to find the following solution

```python
import google
if config.DEVELOPMENT:
  google.__path__.append('./lib/google')
else:
  google.__path__.append('lib.zip/google')
```

Thanks.

**Comment by lipis** [comment]
So I'll close this one..

**Comment by nicoTrombon** [comment]
@ofl Could you explain your solution a little? I have the same problem but want to be able to use global google and the lib/google.auth as well

**Comment by ofl** [comment]
@nicoTrombon

I do not know if it will help, but it was a code that was working 5 months ago.

requirements.txt

```txt
blinker==1.4
flask-login==0.4.0
flask-oauthlib==0.9.3
flask-restful==0.3.5
flask-wtf==0.13.1
flask==0.11.1
pyjwt==1.4.2
unidecode==0.4.19
webargs==1.4.0

google-auth==0.5.0
requests==2.12.4
oauth2client==4.0.0
python-firebase-gae==1.0.1
requests-toolbelt==0.7.0
```

main/api/fb_auth.py

```python
# coding: utf-8

from __future__ import absolute_import

import flask
import requests_toolbelt.adapters.appengine

import config
import model

import google
if config.DEVELOPMENT:
  google.__path__.append('./lib/google')
else:
  google.__path__.append('lib.zip/google')

from google.appengine.ext import ndb
import google.auth.transport.requests as transport_request
import google.oauth2.id_token as oauth2_id_token

requests_toolbelt.adapters.appengine.monkeypatch()
HTTP_REQUEST = transport_request.Request()


def get_app_user_db():
    """
    Firebaseによる認証
    成功するとAppUserモデル、失敗するとNoneを返す
    AppUserが作成されていない場合はその場で作成する
    """
    app_user_db = None
    id_token = ''
    claims = None
    user_id = ''

    if config.DEVELOPMENT:
        user_id = 'test_user_198273'
        name = user_id
    else:
        id_token = flask.request.headers['Authorization'].split(' ').pop()
        claims = oauth2_id_token.verify_firebase_token(id_token, HTTP_REQUEST)
        if not claims:
            return None
        user_id = claims.get('user_id', '')
        name = claims.get('name', '')

    if user_id == '':
        return None

    app_user_key = ndb.Key('AppUser', user_id)
    app_user_db = app_user_key.get()
    if not app_user_db:
        app_user_db = model.AppUser(id=user_id, name=name)
        app_user_db.put()

    return app_user_db
```

**Comment by nicoTrombon** [comment]
@ofl 
Thank you!

Why do you add this in production:
`google.__path__.append('lib.zip/google')`
?

**Comment by ofl** [comment]
@nicoTrombon 

When I tried it, an error occurred in the production environment without that line.

**Comment by gmist** [comment]
@nicoTrombon 
this line adds one more path to find the subpackages of module `google`. [More info about `__path__` attribute](https://docs.python.org/2/tutorial/modules.html#packages-in-multiple-directories).

**Comment by nicoTrombon** [comment]
@ofl @gmist Thank you! 

I didn't have the problem in production env, only running locally with dev_appserver.py, so no need to add that line in my case. I think my problem was a conflict with the global 'google' library in my user site-packages. so my workaround ended up like:
```
import os
if os.getenv('SERVER_SOFTWARE', '').startswith('Google App Engine/'):
  # Production, no need to alter anything
  pass
else:
  # Local development server
  google.__path__.pop(0)  # remove /home/<username>/.local/lib/python2.7/site-packages/google
  logging.warning(google.__path__)  # to inspect the final __path__ of module google 
```

The log in development server ended up showing:
`['<google-cloud-sdk-path>/platform/google_appengine/google', '<project-path>/lib/google']`

And everything worked just right!
