### ISSUE TITLE
DistributionNotFound: google-cloud-core when trying to use google-cloud-storage

### ISSUE THREAD

**Issue by jakedotio** [gae-init/gae-init#616]
I'm receiving a `DistributionNotFound: google-cloud-core` error when trying to use google-cloud-storage.

To reproduce:

1. git clone gae-init / yarn
2. add `google-cloud-storage==0.22.0` to requirements.txt
3. add `from google.cloud import storage` to top of welcome.py
4. browse /

stack trace:

``` 
File "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 85, in LoadObject
    obj = __import__(path[0])
  File "/Users/jake/code/gae-init-test/main/main.py", line 20, in <module>
    import control
  File "/Users/jake/code/gae-init-test/main/control/__init__.py", line 11, in <module>
    from .welcome import *
  File "/Users/jake/code/gae-init-test/main/control/welcome.py", line 9, in <module>
    from google.cloud import storage
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/google/cloud/storage/__init__.py", line 33, in <module>
    from google.cloud.storage.batch import Batch
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/google/cloud/storage/batch.py", line 30, in <module>
    from google.cloud.storage._http import Connection
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/google/cloud/storage/_http.py", line 17, in <module>
    from google.cloud import _http
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/google/cloud/_http.py", line 33, in <module>
    get_distribution('google-cloud-core').version)
  File "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/platform/google_appengine/lib/setuptools-0.6c11/pkg_resources.py", line 311, in get_distribution
    if isinstance(dist,Requirement): dist = get_provider(dist)
  File "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/platform/google_appengine/lib/setuptools-0.6c11/pkg_resources.py", line 197, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/platform/google_appengine/lib/setuptools-0.6c11/pkg_resources.py", line 666, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/platform/google_appengine/lib/setuptools-0.6c11/pkg_resources.py", line 565, in resolve
    raise DistributionNotFound(req)  # XXX put more info here
DistributionNotFound: google-cloud-core
```

google-cloud's been working through some packaging problems described at https://github.com/GoogleCloudPlatform/google-cloud-python/issues/1893, but that thread seems to indicate that google-cloud-storage should work fine.

**Comment by jakedotio** [comment]
Maybe related:

https://github.com/gae-init/gae-init/issues/596
https://github.com/gae-init/gae-init/issues/559

I had gcloud (0.18.0) working in another gae-init project last year, so I think it broke sometime over the last 8 months.

**Comment by rbubley** [comment]
Perhaps a silly question, but why are you expecting google-cloud-core to be available to you?

**Comment by jakedotio** [comment]
@rbubley It's a requirement installed by google-cloud-storage. It was installed properly by  ```gulp init``` in the project's virtualenv site-packages directory so it should be available.

I do not know whether this is a is a gae-init bug or a homebrew packaging issue (or something else) yet.

I've cloned the project to a fresh cloud storage shell instance and got an error there too: 

```
ERROR    2017-02-25 14:52:24,976 wsgi.py:263] 
Traceback (most recent call last):
  File "/google/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/google/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/google/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 85, in LoadObject
    obj = __import__(path[0])
  File "/home/web/code/cloudpayback/main/main.py", line 5, in <module>
    import config
  File "/home/web/code/cloudpayback/main/config.py", line 30, in <module>
    import model
  File "/home/web/code/cloudpayback/main/model/__init__.py", line 3, in <module>
    from .base import Base
  File "/home/web/code/cloudpayback/main/model/base.py", line 12, in <module>
    import util
  File "/home/web/code/cloudpayback/main/util.py", line 28, in <module>
    from google.cloud import storage
ImportError: cannot import name storage
```

google-cloud-storage is not installed in the system site-packages (fresh install), but it is in the virtualenv site-packages for the project. Could it be related to the way we insert paths for third party libs?

**Comment by lipis** [comment]
@jakedotio can you check if it's actually fixed?! It would great :D

**Comment by halsafar** [comment]
I get this issue with storage and bigquery.

**Comment by lipis** [comment]
Still an issue?!

**Comment by jakedotio** [comment]
Yes, still an issue. This library used to work on App Engine Standard and does not anymore.

https://github.com/GoogleCloudPlatform/google-cloud-python

> Note
> These libraries currently do not run on Google App Engine Standard. We are actively working on adding this support.

**Comment by lipis** [comment]
So I think we can close this one :|
