### ISSUE TITLE
Does not seem to pick css style in ubuntu

### ISSUE THREAD

**Issue by adsodemelk** [gae-init/gae-init#662]
Hello,
Does anyone encountered this problem in ubuntu 16.04LTS.
After running `gulp` locally, the server seems to be up and running but the welcome page has plain text and it does not pick up css/bootstrap style.
I did run `curl https://raw.githubusercontent.com/gae-init/gae-init/master/bin/requirements_linux.sh | bash`
to get the dependencies.
and `npm install` before `gulp`
Thanks for any help provided.

**Comment by lipis** [comment]
Can you kill any instance of Python and then execute `gulp` and paste here the output?

**Comment by adsodemelk** [comment]
I am using a conda environment to run python 2 as my defult one is p3
`conda create -n gae-init`
 there is an error in browser-sync but not sure if it is related


(gae-init) lopezcas@lopezcas-HP:~/webdev/phonebook$ gulp
[14:08:17] Using gulpfile ~/webdev/phonebook/gulpfile.js
[14:08:17] Starting 'default'...
[14:08:17] Starting 'run'...
[14:08:17] Starting 'init'...
[14:08:17] Starting 'pip'...
[14:08:17] Finished 'run' after 15 ms
[14:08:17] Starting 'watch'...
[14:08:17]  $ python run.py -d
[14:08:18] Finished 'pip' after 860 ms
[14:08:18] Starting 'bower'...
[14:08:18]  $ node_modules/.bin/bower install
[14:08:19] Finished 'bower' after 567 ms
[14:08:19] Starting 'copy_bower_files'...
[14:08:19] Starting 'ext:dev'...
(node) warning: possible EventEmitter memory leak detected. 11 task_stop listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Gulp.addListener (events.js:239:17)
    at /home/lopezcas/webdev/phonebook/node_modules/gulp-sequence/index.js:64:12
    at apply (/home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:362:38)
    at tryRun (/home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:232:19)
    at runThunk (/home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:225:15)
    at /home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:322:49
    at apply (/home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:362:38)
    at tryRun (/home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:232:19)
    at runThunk (/home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:225:15)
    at continuation (/home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:172:10)
    at child (/home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:163:24)
    at thunkFunction (/home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:153:14)
    at /home/lopezcas/webdev/phonebook/gulp/tasks/watch.coffee:33:5
    at write (/home/lopezcas/webdev/phonebook/node_modules/gulp-watch/index.js:147:3)
    at /home/lopezcas/webdev/phonebook/node_modules/gulp-watch/index.js:130:5

(node) warning: possible EventEmitter memory leak detected. 11 task_not_found listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Gulp.addListener (events.js:239:17)
    at /home/lopezcas/webdev/phonebook/node_modules/gulp-sequence/index.js:65:12
    at apply (/home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:362:38)
    at tryRun (/home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:232:19)
    at runThunk (/home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:225:15)
    at /home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:322:49
    at apply (/home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:362:38)
    at tryRun (/home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:232:19)
    at runThunk (/home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:225:15)
    at continuation (/home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:172:10)
    at child (/home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:163:24)
    at thunkFunction (/home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:153:14)
    at /home/lopezcas/webdev/phonebook/gulp/tasks/watch.coffee:33:5
    at write (/home/lopezcas/webdev/phonebook/node_modules/gulp-watch/index.js:147:3)
    at /home/lopezcas/webdev/phonebook/node_modules/gulp-watch/index.js:130:5

(node) warning: possible EventEmitter memory leak detected. 11 task_err listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Gulp.addListener (events.js:239:17)
    at /home/lopezcas/webdev/phonebook/node_modules/gulp-sequence/index.js:67:12
    at apply (/home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:362:38)
    at tryRun (/home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:232:19)
    at runThunk (/home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:225:15)
    at /home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:322:49
    at apply (/home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:362:38)
    at tryRun (/home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:232:19)
    at runThunk (/home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:225:15)
    at continuation (/home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:172:10)
    at child (/home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:163:24)
    at thunkFunction (/home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:153:14)
    at /home/lopezcas/webdev/phonebook/gulp/tasks/watch.coffee:33:5
    at write (/home/lopezcas/webdev/phonebook/node_modules/gulp-watch/index.js:147:3)
    at /home/lopezcas/webdev/phonebook/node_modules/gulp-watch/index.js:130:5

(node) warning: possible EventEmitter memory leak detected. 11 task_recursion listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Gulp.addListener (events.js:239:17)
    at /home/lopezcas/webdev/phonebook/node_modules/gulp-sequence/index.js:66:12
    at apply (/home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:362:38)
    at tryRun (/home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:232:19)
    at runThunk (/home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:225:15)
    at /home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:322:49
    at apply (/home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:362:38)
    at tryRun (/home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:232:19)
    at runThunk (/home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:225:15)
    at continuation (/home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:172:10)
    at child (/home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:163:24)
    at thunkFunction (/home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:153:14)
    at /home/lopezcas/webdev/phonebook/gulp/tasks/watch.coffee:33:5
    at write (/home/lopezcas/webdev/phonebook/node_modules/gulp-watch/index.js:147:3)
    at /home/lopezcas/webdev/phonebook/node_modules/gulp-watch/index.js:130:5

[14:08:19] Finished 'ext:dev' after 124 ms
[14:08:19] Starting 'ext:dev'...
[14:08:19] Finished 'ext:dev' after 90 ms
[14:08:19] Starting 'ext:dev'...
[14:08:19] Finished 'ext:dev' after 72 ms
[14:08:19] Starting 'ext:dev'...
[14:08:19] Finished 'ext:dev' after 55 ms
[14:08:19] Starting 'ext:dev'...
[14:08:19] Finished 'ext:dev' after 57 ms
[14:08:19] Starting 'ext:dev'...
[14:08:19] Finished 'ext:dev' after 58 ms
[14:08:19] Starting 'ext:dev'...
[14:08:19] Finished 'ext:dev' after 55 ms
[14:08:19] Starting 'ext:dev'...
[14:08:19] Finished 'ext:dev' after 52 ms
[14:08:19] Starting 'ext:dev'...
[14:08:19] Finished 'ext:dev' after 57 ms
[14:08:19] Starting 'ext:dev'...
[14:08:19] Finished 'copy_bower_files' after 832 ms
[14:08:19] Finished 'init' after 2.26 s
[14:08:19] Starting 'script:dev'...
[14:08:19] Starting 'style:dev'...
{ [TypeError: this is not a typed array.]
  name: 'TypeError',
  message: 'this is not a typed array.',
  stack: 'TypeError: this is not a typed array.\n    at Function.from (native)\n    at /home/lopezcas/webdev/phonebook/node_modules/gulp-autoprefixer/index.js:25:27\n    at process._tickCallback (node.js:368:9)\n',
  fileName: '/home/lopezcas/webdev/phonebook/main/static/src/style/style.css',
  showStack: true,
  showProperties: true,
  plugin: 'gulp-autoprefixer' }
[14:08:21] Finished 'style:dev' after 1.91 s
[14:08:21] Finished 'ext:dev' after 1.96 s
[14:08:21] Finished 'script:dev' after 1.92 s
[14:08:21] Starting 'browser-sync'...
[14:08:21]  $ python run.py -s
[BS] Proxying: http://127.0.0.1:8080
[BS] Access URLs:
 -------------------------------------
       Local: http://localhost:3000
    External: http://192.168.0.48:3000
 -------------------------------------
          UI: http://localhost:3001
 UI External: http://192.168.0.48:3001
 -------------------------------------
[14:08:22] 'browser-sync' errored after 238 ms
[14:08:22] Error: watch /home/lopezcas/webdev/phonebook/main/lib/unidecode/x0b3.py ENOSPC
    at exports._errnoException (util.js:870:11)
    at FSWatcher.start (fs.js:1234:19)
    at Object.fs.watch (fs.js:1262:11)
    at createFsWatchInstance (/home/lopezcas/webdev/phonebook/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/lopezcas/webdev/phonebook/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/lopezcas/webdev/phonebook/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleFile (/home/lopezcas/webdev/phonebook/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at FSWatcher.<anonymous> (/home/lopezcas/webdev/phonebook/node_modules/chokidar/lib/nodefs-handler.js:473:21)
    at FSReqWrap.oncomplete (fs.js:82:15)

INFO     2017-05-14 13:08:23,369 devappserver2.py:692] Skipping SDK update check.
INFO     2017-05-14 13:08:23,490 api_server.py:272] Starting API server at: http://localhost:41515
WARNING  2017-05-14 13:08:23,497 inotify_file_watcher.py:200] There are too many directories in your application for changes in all of them to be monitored. You may have to restart the development server to see some changes to your files.
INFO     2017-05-14 13:08:23,497 dispatcher.py:205] Starting module "default" running at: http://127.0.0.1:8080
INFO     2017-05-14 13:08:23,498 admin_server.py:116] Starting admin server at: http://localhost:8081
INFO     2017-05-14 13:08:26,047 recording.py:676] Saved; key: __appstats__:006000, part: 25 bytes, full: 1021 bytes, overhead: 0.000 + 0.002; link: http://127.0.0.1:8080/_ah/stats/details?time=1494767306044
INFO     2017-05-14 13:08:26,051 module.py:813] default: "GET /_ah/warmup HTTP/1.1" 200 7

**Comment by adsodemelk** [comment]
```
(gae-init) lopezcas@lopezcas-HP:~/webdev/phonebook$ gulp
[14:08:17] Using gulpfile ~/webdev/phonebook/gulpfile.js
[14:08:17] Starting 'default'...
[14:08:17] Starting 'run'...
[14:08:17] Starting 'init'...
[14:08:17] Starting 'pip'...
[14:08:17] Finished 'run' after 15 ms
[14:08:17] Starting 'watch'...
[14:08:17]  $ python run.py -d
[14:08:18] Finished 'pip' after 860 ms
[14:08:18] Starting 'bower'...
[14:08:18]  $ node_modules/.bin/bower install
[14:08:19] Finished 'bower' after 567 ms
[14:08:19] Starting 'copy_bower_files'...
[14:08:19] Starting 'ext:dev'...
(node) warning: possible EventEmitter memory leak detected. 11 task_stop listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Gulp.addListener (events.js:239:17)
    at /home/lopezcas/webdev/phonebook/node_modules/gulp-sequence/index.js:64:12
    at apply (/home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:362:38)
    at tryRun (/home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:232:19)
    at runThunk (/home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:225:15)
    at /home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:322:49
    at apply (/home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:362:38)
    at tryRun (/home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:232:19)
    at runThunk (/home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:225:15)
    at continuation (/home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:172:10)
    at child (/home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:163:24)
    at thunkFunction (/home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:153:14)
    at /home/lopezcas/webdev/phonebook/gulp/tasks/watch.coffee:33:5
    at write (/home/lopezcas/webdev/phonebook/node_modules/gulp-watch/index.js:147:3)
    at /home/lopezcas/webdev/phonebook/node_modules/gulp-watch/index.js:130:5

(node) warning: possible EventEmitter memory leak detected. 11 task_not_found listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Gulp.addListener (events.js:239:17)
    at /home/lopezcas/webdev/phonebook/node_modules/gulp-sequence/index.js:65:12
    at apply (/home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:362:38)
    at tryRun (/home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:232:19)
    at runThunk (/home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:225:15)
    at /home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:322:49
    at apply (/home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:362:38)
    at tryRun (/home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:232:19)
    at runThunk (/home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:225:15)
    at continuation (/home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:172:10)
    at child (/home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:163:24)
    at thunkFunction (/home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:153:14)
    at /home/lopezcas/webdev/phonebook/gulp/tasks/watch.coffee:33:5
    at write (/home/lopezcas/webdev/phonebook/node_modules/gulp-watch/index.js:147:3)
    at /home/lopezcas/webdev/phonebook/node_modules/gulp-watch/index.js:130:5

(node) warning: possible EventEmitter memory leak detected. 11 task_err listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Gulp.addListener (events.js:239:17)
    at /home/lopezcas/webdev/phonebook/node_modules/gulp-sequence/index.js:67:12
    at apply (/home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:362:38)
    at tryRun (/home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:232:19)
    at runThunk (/home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:225:15)
    at /home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:322:49
    at apply (/home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:362:38)
    at tryRun (/home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:232:19)
    at runThunk (/home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:225:15)
    at continuation (/home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:172:10)
    at child (/home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:163:24)
    at thunkFunction (/home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:153:14)
    at /home/lopezcas/webdev/phonebook/gulp/tasks/watch.coffee:33:5
    at write (/home/lopezcas/webdev/phonebook/node_modules/gulp-watch/index.js:147:3)
    at /home/lopezcas/webdev/phonebook/node_modules/gulp-watch/index.js:130:5

(node) warning: possible EventEmitter memory leak detected. 11 task_recursion listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Gulp.addListener (events.js:239:17)
    at /home/lopezcas/webdev/phonebook/node_modules/gulp-sequence/index.js:66:12
    at apply (/home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:362:38)
    at tryRun (/home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:232:19)
    at runThunk (/home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:225:15)
    at /home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:322:49
    at apply (/home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:362:38)
    at tryRun (/home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:232:19)
    at runThunk (/home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:225:15)
    at continuation (/home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:172:10)
    at child (/home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:163:24)
    at thunkFunction (/home/lopezcas/webdev/phonebook/node_modules/thunks/thunks.js:153:14)
    at /home/lopezcas/webdev/phonebook/gulp/tasks/watch.coffee:33:5
    at write (/home/lopezcas/webdev/phonebook/node_modules/gulp-watch/index.js:147:3)
    at /home/lopezcas/webdev/phonebook/node_modules/gulp-watch/index.js:130:5

[14:08:19] Finished 'ext:dev' after 124 ms
[14:08:19] Starting 'ext:dev'...
[14:08:19] Finished 'ext:dev' after 90 ms
[14:08:19] Starting 'ext:dev'...
[14:08:19] Finished 'ext:dev' after 72 ms
[14:08:19] Starting 'ext:dev'...
[14:08:19] Finished 'ext:dev' after 55 ms
[14:08:19] Starting 'ext:dev'...
[14:08:19] Finished 'ext:dev' after 57 ms
[14:08:19] Starting 'ext:dev'...
[14:08:19] Finished 'ext:dev' after 58 ms
[14:08:19] Starting 'ext:dev'...
[14:08:19] Finished 'ext:dev' after 55 ms
[14:08:19] Starting 'ext:dev'...
[14:08:19] Finished 'ext:dev' after 52 ms
[14:08:19] Starting 'ext:dev'...
[14:08:19] Finished 'ext:dev' after 57 ms
[14:08:19] Starting 'ext:dev'...
[14:08:19] Finished 'copy_bower_files' after 832 ms
[14:08:19] Finished 'init' after 2.26 s
[14:08:19] Starting 'script:dev'...
[14:08:19] Starting 'style:dev'...
{ [TypeError: this is not a typed array.]
  name: 'TypeError',
  message: 'this is not a typed array.',
  stack: 'TypeError: this is not a typed array.\n    at Function.from (native)\n    at /home/lopezcas/webdev/phonebook/node_modules/gulp-autoprefixer/index.js:25:27\n    at process._tickCallback (node.js:368:9)\n',
  fileName: '/home/lopezcas/webdev/phonebook/main/static/src/style/style.css',
  showStack: true,
  showProperties: true,
  plugin: 'gulp-autoprefixer' }
[14:08:21] Finished 'style:dev' after 1.91 s
[14:08:21] Finished 'ext:dev' after 1.96 s
[14:08:21] Finished 'script:dev' after 1.92 s
[14:08:21] Starting 'browser-sync'...
[14:08:21]  $ python run.py -s
[BS] Proxying: http://127.0.0.1:8080
[BS] Access URLs:
 -------------------------------------
       Local: http://localhost:3000
    External: http://192.168.0.48:3000
 -------------------------------------
          UI: http://localhost:3001
 UI External: http://192.168.0.48:3001
 -------------------------------------
[14:08:22] 'browser-sync' errored after 238 ms
[14:08:22] Error: watch /home/lopezcas/webdev/phonebook/main/lib/unidecode/x0b3.py ENOSPC
    at exports._errnoException (util.js:870:11)
    at FSWatcher.start (fs.js:1234:19)
    at Object.fs.watch (fs.js:1262:11)
    at createFsWatchInstance (/home/lopezcas/webdev/phonebook/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/lopezcas/webdev/phonebook/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/lopezcas/webdev/phonebook/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleFile (/home/lopezcas/webdev/phonebook/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at FSWatcher.<anonymous> (/home/lopezcas/webdev/phonebook/node_modules/chokidar/lib/nodefs-handler.js:473:21)
    at FSReqWrap.oncomplete (fs.js:82:15)

INFO     2017-05-14 13:08:23,369 devappserver2.py:692] Skipping SDK update check.
INFO     2017-05-14 13:08:23,490 api_server.py:272] Starting API server at: http://localhost:41515
WARNING  2017-05-14 13:08:23,497 inotify_file_watcher.py:200] There are too many directories in your application for changes in all of them to be monitored. You may have to restart the development server to see some changes to your files.
INFO     2017-05-14 13:08:23,497 dispatcher.py:205] Starting module "default" running at: http://127.0.0.1:8080
INFO     2017-05-14 13:08:23,498 admin_server.py:116] Starting admin server at: http://localhost:8081
INFO     2017-05-14 13:08:26,047 recording.py:676] Saved; key: __appstats__:006000, part: 25 bytes, full: 1021 bytes, overhead: 0.000 + 0.002; link: http://127.0.0.1:8080/_ah/stats/details?time=1494767306044
INFO     2017-05-14 13:08:26,051 module.py:813] default: "GET /_ah/warmup HTTP/1.1" 200 7

```

**Comment by adsodemelk** [comment]
(gae-init) is a python2 environment created with conda: `conda create -n gae-init python=2.7` as my default python is python3

**Comment by adsodemelk** [comment]
Looking at the log and this http://stackoverflow.com/questions/36899888/getting-typeerror-this-is-not-a-typed-array-using-buffer-from-in-mocha
I was using a pre 6.0.0 version of node.
I updated node:
```
sudo npm cache clean -f
sudo npm install -g n
sudo n stable
```

 and the css works now.
thanks

**Comment by lipis** [comment]
Nice! In general if there are errors in the output when running `gulp` something most likely is not going to work.. I'm glad that now everything is working.. cheers!
