### ISSUE TITLE
ImportError: cannot import name stubs

### ISSUE THREAD

**Issue by trickidicki** [gae-init/gae-init#713]
A fresh download & install of GAE init on Windows using latest GCloud SDK:
```
INFO     2017-09-16 12:14:52,743 module.py:821] default: "GET /_ah/warmup HTTP/1.1" 500 749
INFO     2017-09-16 12:14:53,713 module.py:408] [default] Detected file changes:
  appengine_config.pyc
  path_util.pyc
ERROR    2017-09-16 02:14:54,174 wsgi.py:263]
Traceback (most recent call last):
  File "D:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\runtime\wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "D:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\api\lib_config.py", line 351, in __getattr__
    self._update_configs()
  File "D:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\api\lib_config.py", line 287, in _update_configs
    self._registry.initialize()
INFO     2017-09-16 12:14:54,190 module.py:821] default: "GET /_ah/warmup HTTP/1.1" 500 749
  File "D:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\api\lib_config.py", line 160, in initialize
    import_func(self._modname)
  File "G:\work\python\my-app\main\appengine_config.py", line 17, in <module>
    from google.appengine.tools.devappserver2.python import stubs
ImportError: cannot import name stubs
```

**Comment by asmith26** [comment]
I can confirm I have seen the same problem - as a temporary fix I have commented out the following lines:

*main/appengine_config.py*
```
# import re
# from google.appengine.tools.devappserver2.python import stubs
#
# re_ = stubs.FakeFile._skip_files.pattern.replace('|^lib/.*', '')
# re_ = re.compile(re_)
# stubs.FakeFile._skip_files = re_
```

and *main/app.yaml*
```
#- ^lib/.*
```

**Comment by benoitpointet** [comment]
It seems the stubs.py file moved into a `runtime` subfolder, so one can also simply replace
```
# from google.appengine.tools.devappserver2.python import stubs
```
with
``` 
# from google.appengine.tools.devappserver2.python.runtime import stubs
```

**Comment by michl-in-pan** [comment]
I am workin on a mac ..yes I can confirm that..stubs.py moved to runtime...change
from google.appengine.tools.devappserver2.python import stubs
to
from google.appengine.tools.devappserver2.python.runtime import stubs

**Comment by lipis** [comment]
Fixed in #719

**Comment by MistriHD** [comment]
Hi, I'm also having this issue. I just installed a fresh download and my `main/appengine_config.py` has the fixed version already:

    from google.appengine.tools.devappserver2.python.runtime import stubs

My error:

    ImportError: cannot import name stubs

**Comment by b-cannon** [comment]
Same here, it just happened to me today when installing the latest gae-init

**Comment by lipis** [comment]
So I guess we have to reopen this.. will check tomorrow what is going on.. and what changed.. :)
