### ISSUE TITLE
cannot import name cli_parser

### ISSUE THREAD

**Issue by michl-in-pan** [gae-init/gae-init#737]
Hi 
I have problems wit this error since today. I checked if cli_parser.py is in the right directory but it is all there...did somebody experience that?

WARNING:root:/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/lib/cacerts/urlfetch_cacerts.txt missing; without this urlfetch will not be able to validate SSL certificates.
Traceback (most recent call last):
  File "/Users/michl/google-cloud-sdk/platform/google_appengine/dev_appserver.py", line 103, in <module>
    _run_file(__file__, globals())
  File "/Users/michl/google-cloud-sdk/platform/google_appengine/dev_appserver.py", line 97, in _run_file
    execfile(_PATHS.script_file(script_name), globals_)
  File "/Users/michl/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 29, in <module>
    from google.appengine.tools.devappserver2 import cli_parser
ImportError: cannot import name cli_parser

**Comment by michl-in-pan** [comment]
I resolved it :-) ....Upgrade your python version to 2.17.14 if you experience the same error
I used python 2.17.13 before
Maybe a gloud components update produced this error because it always worked before
