### ISSUE TITLE
Stubs again

### ISSUE THREAD

**Issue by rbubley** [gae-init/gae-init#797]
I've recently started seeing:
```
Traceback (most recent call last):
  File "/Users/russ/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/Users/russ/google-cloud-sdk/platform/google_appengine/google/appengine/api/lib_config.py", line 351, in __getattr__
    self._update_configs()
  File "/Users/russ/google-cloud-sdk/platform/google_appengine/google/appengine/api/lib_config.py", line 287, in _update_configs
    self._registry.initialize()
  File "/Users/russ/google-cloud-sdk/platform/google_appengine/google/appengine/api/lib_config.py", line 160, in initialize
    import_func(self._modname)
  File "/<redacted>/main/appengine_config.py", line 19, in <module>
    from google.appengine.tools.devappserver2.python.runtime import stubs
ImportError: cannot import name stubs
```

This is with gae-init 5.10.0, so includes the changes from  #719.

Anyone else seeing this, or is it something up with my environment?

**Comment by mroswell** [comment]
I encountered the same error. I applied asmith26's 9//16/17 "temporary fix" from #713 (locally) to be able to proceed.

**Comment by cloudwizard** [comment]
I am seeing it in cloud shell

**Comment by jakedotio** [comment]
I am seeing it as well.

**Comment by lipis** [comment]
So what should we do with this one?!

**Comment by rbubley** [comment]
I’m working on other projects at the moment so can’t focus on this, but it seemed to me that the issue is how we try to import the stubs function: the function does not (now) appear in the __init__.py, so we need to import it differently.
