### ISSUE TITLE
Unexpected attribute 'gulpdev_appserverservice' for object of type AppInfoExternal.   in "main/app.yaml", line 1

### ISSUE THREAD

**Issue by do-n-khanh** [gae-init/gae-init#873]
I follow the tutorial http://docs.gae-init.appspot.com/quickstart/, but using Cloud Shell
cd hello
gulp
Then I got this error

Traceback (most recent call last):
  File "/google/google-cloud-sdk/platform/google_appengine/dev_appserver.py", line 96, in <module>
    _run_file(__file__, globals())
  File "/google/google-cloud-sdk/platform/google_appengine/dev_appserver.py", line 90, in _run_file
    execfile(_PATHS.script_file(script_name), globals_)
  File "/google/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 454, in <module>
    main()
  File "/google/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 442, in main
    dev_server.start(options)
  File "/google/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 110, in start
    env_variables=parsed_env_variables)
  File "/google/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 933, in __init__
    env_variables)
  File "/google/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 133, in __init__
    self._config_path)
  File "/google/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 499, in _parse_conf
iguration
    config, files = appinfo_includes.ParseAndReturnIncludePaths(f)
  File "/google/google-cloud-sdk/platform/google_appengine/google/appengine/api/appinfo_includes.py", line 82, in ParseAndReturnIncludePaths
    appyaml = appinfo.LoadSingleAppInfo(appinfo_file)
  File "/google/google-cloud-sdk/platform/google_appengine/google/appengine/api/appinfo.py", line 2621, in LoadSingleAppInfo
    listener.Parse(app_info)
  File "/google/google-cloud-sdk/platform/google_appengine/google/appengine/api/yaml_listener.py", line 227, in Parse
    self._HandleEvents(self._GenerateEventParameters(stream, loader_class))
  File "/google/google-cloud-sdk/platform/google_appengine/google/appengine/api/yaml_listener.py", line 178, in _HandleEvents
    raise yaml_errors.EventError(e, event_object)
google.appengine.api.yaml_errors.EventError: Unexpected attribute 'gulpdev_appserverservice' for object of type AppInfoExternal.
  in "main/app.yaml", line 1, column 27

How can I try gae-init on Cloud Shell?

**Comment by lipis** [comment]
Sorry for a late reply.. if that still an issue please reply.
