### ISSUE TITLE
IOError: [Errno 2] No such file or directory: 'lib.zip'

### ISSUE THREAD

**Issue by pttdev** [gae-init/gae-init#876]
I tried to deploy gae-init from cloud shell and it show like title. Here is the log:
Traceback (most recent call last):
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/277b61042b697c7a_unzipped/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/277b61042b697c7a_unzipped/python27_lib/versions/1/google/appengine/api/lib_config.py", line 351, in __getattr__
    self._update_configs()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/277b61042b697c7a_unzipped/python27_lib/versions/1/google/appengine/api/lib_config.py", line 287, in _update_configs
    self._registry.initialize()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/277b61042b697c7a_unzipped/python27_lib/versions/1/google/appengine/api/lib_config.py", line 160, in initialize
    import_func(self._modname)
  File "/base/data/home/apps/b~check-code/20180612t140443.410380967680624882/appengine_config.py", line 12, in <module>
    sys_path_insert('lib.zip')
  File "/base/data/home/apps/b~check-code/20180612t140443.410380967680624882/path_util.py", line 54, in sys_path_insert
    path_package_path(dirname, get_shadows_zip(dirname))
  File "/base/data/home/apps/b~check-code/20180612t140443.410380967680624882/path_util.py", line 29, in get_shadows_zip
    with zipfile.ZipFile(filename) as lib_zip:
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/277b61042b697c7a_unzipped/python27_dist/lib/python2.7/zipfile.py", line 756, in __init__
    self.fp = open(file, modeDict[mode])
IOError: [Errno 2] No such file or directory: 'lib.zip'

**Comment by lipis** [comment]
what did you run in order to deploy it..?

**Comment by gbonfiglio** [comment]
I can replicate with the steps from the quickstart, run in Google Cloud Shell:

git clone https://github.com/gae-init/gae-init.git test
cd test
npm install
gulp deploy --project=test

Any idea? (first time user here)

**Comment by gmist** [comment]
@gbonfiglio 

1. go to https://console.cloud.google.com/appengine
2. create new project _your-project-name_
3. gulp deploy --project=_your-project-name_
4. check http://your-project-name.appspot.com/

**Comment by gbonfiglio** [comment]
@gmist not sure how this helps - I have a project, and I'm deploying to that project. The fact that I get the error after deploying kind of means the deployment is successful, right?

**Comment by gmist** [comment]
Hmm, probably something is wrong with Google Cloud Shell

**Comment by patrickmpoon** [comment]
@gbonfiglio, were you able to resolve this issue?  I'm seeing the same.  The cloud console is showing the following:
```
OSError: [Errno 2] No such file or directory: 'lib.zip/babel/locale-data'
at top-level template code (/base/data/home/apps/p~zazenai-hometo/20180708t224641.411002733097337842/templates/error.html:1)
at handle_exception (lib.zip/jinja2/environment.py:780)
at render (lib.zip/jinja2/environment.py:1008)
at _render (lib.zip/flask/templating.py:117)
at render_template (lib.zip/flask/templating.py:135)
at error_handler (/base/data/home/apps/p~zazenai-hometo/20180708t224641.411002733097337842/control/error.py:41)
at handle_exception (lib.zip/flask/app.py:1748)
at error_router (lib.zip/flask_restful/__init__.py:273)
at wsgi_app (lib.zip/flask/app.py:2295)
at __call__ (lib.zip/flask/app.py:2309)
at appstats_wsgi_wrapper (/base/alloc/tmpfs/dynamic_runtimes/python27/b93f87cfaa0115e5_unzipped/python27_lib/versions/1/google/appengine/ext/appstats/recording.py:1287)
at Handle (/base/alloc/tmpfs/dynamic_runtimes/python27/b93f87cfaa0115e5_unzipped/python27_lib/versions/1/google/appengine/runtime/wsgi.py:268)
```

**Comment by gbonfiglio** [comment]
@patrickmpoon unfortunately I wasn't and gave up after a while.

**Comment by rbubley** [comment]
PR #900 may help in diagnosing this.

**Comment by mdxs** [comment]
Today, I've just tried this myself using the Google Cloud Shell (note: my first GCS session...) and confirm it didn't work the first time (using out-dated `npm install` and even not with `npm install yarn && gulp deploy`). It showed the `IOError: [Errno 2] No such file or directory: 'lib.zip'` issue as reported by @pttdev  in the `/logs/viewer?project=` and the resulting `/appengine/versions?project=` was only 169.1 KB in size.

These are the steps followed:
1. go to https://console.cloud.google.com/appengine
1. create new project _my-project-name_
1. go to https://console.cloud.google.com/cloudshell/environment/view?project=my-project-name&fromcloudshell=true
1. `git clone https://github.com/gae-init/gae-init.git my-project-name`
1. `cd my-project-name`
1. `yarn` &rarr; this failed with a `-bash: yarn: command not found`
1. `npm install` &rarr; out-dated but allowed me to continue
1. `gulp deploy --project=my-project-name` (and answered "y" to continue deployment)
1. `gcloud app logs tail -s default` (as this was shown in the output)
1. while that was running, visited `https://my-poject-name.appspot.com/` in a browser; which only showed _"Oh no...! Something went wrong :(   Please check back in a bit."_

Observed the following output in GCS (from the tail on logs):
```
Waiting for new log entries...
2018-10-29 16:03:26 default[20181029t170215]  "GET / HTTP/1.1" 500
2018-10-29 16:04:35 default[20181029t170215]  "GET / HTTP/1.1" 500
2018-10-29 16:04:36 default[20181029t170215]  "GET /favicon.ico HTTP/1.1" 200
```

While the https://console.cloud.google.com/logs/viewer?project=my-project-name showed the `IOError: [Errno 2] No such file or directory: 'lib.zip'` issue for the 500s.

So it seems that there are two issues:
1. `yarn` doesn't work in GCS (at least not out-of-the-box)
2. out-dated instructions with `npm install` lead to this problem in GCS

**Comment by lipis** [comment]
I think this is resolved now... if anything please open a new issue or post here.
