### ISSUE TITLE
PermanentTaskFailure: 'module' object has no attribute 'admin_required'

### ISSUE THREAD

**Issue by do-n-khanh** [gae-init/gae-init#933]
I have deferred.defer() task queue which definitely does not use admin_required at all.

```
def mytask(twaccount_db_key):
  twaccount_db = twaccount_db_key.get()
  ##Do something
```

And here is how I call mytask:
```
def callmytask():
   ....
   deferred.defer(mytask,key)

```

And I use cron job to callmytask every 5 minutes:

```
cron:
- description: Testing
  url: /callmytask/
  schedule: every 5 minutes

```

You can see. I definitely do not use  admin_required
This task is in push queue. It normally run well.
However, when I deploy app everytime, GAE shut down/restart all instances. This brings all the python model loads again. And I can not understand why it says : 'module' object has no attribute 'admin_required'.

Below is the log :

```
{
 httpRequest: {
  status: 200   
 }
 insertId: "5b872c560002837fc95f57b2"  
 labels: {
  clone_id: "00c61b117c7bd7870da068f1673ac1978b25c0a665549789a612977f2f75873d061859acf7"   
 }
 logName: "projects/myappid/logs/appengine.googleapis.com%2Frequest_log"  
 operation: {
  first: true   
  id: "5b872c5300ff04cc7547f99d010001737e74776974746172646f746a70000131000100"   
  last: true   
  producer: "appengine.googleapis.com/request_id"   
 }
 protoPayload: {
  @type: "type.googleapis.com/google.appengine.logging.v1.RequestLog"   
  appEngineRelease: "1.9.54"   
  appId: "s~myappid"   
  cost: 9.387e-9   
  endTime: "2018-08-29T23:29:26.164324Z"   
  finished: true   
  first: true   
  host: "myappid.appspot.com"   
  httpVersion: "HTTP/1.1"   
  instanceId: "00c61b117c7bd7870da068f1673ac1978b25c0a665549789a612977f2f75873d061859acf7"   
  instanceIndex: -1   
  ip: "0.1.0.2"   
  latency: "2.849839s"   
  line: [
   0: {
    logMessage: "X-Appengine-Taskretrycount:0, X-Appengine-Tasketa:1535585363.2146449, X-Appengine-Current-Namespace:, X-Appengine-Taskname:2581527357831445774, X-Appengine-Taskexecutioncount:0, X-Appengine-Queuename:default, X-Appengine-Country:ZZ"     
    severity: "INFO"     
    time: "2018-08-29T23:29:25.035116Z"     
   }
   1: {
    logMessage: "Successfuly imported extension module "markdown.extensions.extra"."     
    severity: "DEBUG"     
    time: "2018-08-29T23:29:26.095810Z"     
   }
   2: {
    logMessage: "Successfuly imported extension module "markdown.extensions.smart_strong"."     
    severity: "DEBUG"     
    time: "2018-08-29T23:29:26.097279Z"     
   }
   3: {
    logMessage: "Successfully loaded extension "markdown.extensions.smart_strong.SmartEmphasisExtension"."     
    severity: "DEBUG"     
    time: "2018-08-29T23:29:26.098238Z"     
   }
   4: {
    logMessage: "Successfuly imported extension module "markdown.extensions.fenced_code"."     
    severity: "DEBUG"     
    time: "2018-08-29T23:29:26.105811Z"     
   }
   5: {
    logMessage: "Successfully loaded extension "markdown.extensions.fenced_code.FencedCodeExtension"."     
    severity: "DEBUG"     
    time: "2018-08-29T23:29:26.106026Z"     
   }
   6: {
    logMessage: "Successfuly imported extension module "markdown.extensions.footnotes"."     
    severity: "DEBUG"     
    time: "2018-08-29T23:29:26.113109Z"     
   }
   7: {
    logMessage: "Successfully loaded extension "markdown.extensions.footnotes.FootnoteExtension"."     
    severity: "DEBUG"     
    time: "2018-08-29T23:29:26.113713Z"     
   }
   8: {
    logMessage: "Successfuly imported extension module "markdown.extensions.attr_list"."     
    severity: "DEBUG"     
    time: "2018-08-29T23:29:26.130319Z"     
   }
   9: {
    logMessage: "Successfully loaded extension "markdown.extensions.attr_list.AttrListExtension"."     
    severity: "DEBUG"     
    time: "2018-08-29T23:29:26.130616Z"     
   }
   10: {
    logMessage: "Successfuly imported extension module "markdown.extensions.def_list"."     
    severity: "DEBUG"     
    time: "2018-08-29T23:29:26.133290Z"     
   }
   11: {
    logMessage: "Successfully loaded extension "markdown.extensions.def_list.DefListExtension"."     
    severity: "DEBUG"     
    time: "2018-08-29T23:29:26.133647Z"     
   }
   12: {
    logMessage: "Successfuly imported extension module "markdown.extensions.tables"."     
    severity: "DEBUG"     
    time: "2018-08-29T23:29:26.138461Z"     
   }
   13: {
    logMessage: "Successfully loaded extension "markdown.extensions.tables.TableExtension"."     
    severity: "DEBUG"     
    time: "2018-08-29T23:29:26.138782Z"     
   }
   14: {
    logMessage: "Successfuly imported extension module "markdown.extensions.abbr"."     
    severity: "DEBUG"     
    time: "2018-08-29T23:29:26.141640Z"     
   }
   15: {
    logMessage: "Successfully loaded extension "markdown.extensions.abbr.AbbrExtension"."     
    severity: "DEBUG"     
    time: "2018-08-29T23:29:26.141923Z"     
   }
   16: {
    logMessage: "Successfully loaded extension "markdown.extensions.extra.ExtraExtension"."     
    severity: "DEBUG"     
    time: "2018-08-29T23:29:26.142560Z"     
   }
   17: {
    logMessage: "Permanent failure attempting to execute task
Traceback (most recent call last):
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/573c2cae20d3e94a/python27/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 318, in post
    self.run_from_request()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/573c2cae20d3e94a/python27/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 313, in run_from_request
    run(self.request.body)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/573c2cae20d3e94a/python27/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 153, in run
    raise PermanentTaskFailure(e)
PermanentTaskFailure: 'module' object has no attribute 'admin_required'"     
    severity: "ERROR"     
    time: "2018-08-29T23:29:26.152884Z"     
   }

```

Can anybody help me to fix this error.

**Comment by lipis** [comment]
Can you post the complete `mytask` function? (just remove any sensitive data)

**Comment by do-n-khanh** [comment]
@lipis Thanks for reply.

@app.route('/autofavoritetweet/')

```
def autofavoritetweet():
  #Go to each twitter account --> Get N people to follow
  twaccount_dbs = model.TwAccount.query().filter(ndb.GenericProperty('specifiedfavoritestatus') == 'run')
  for twaccount_db in twaccount_dbs:
    #Has error
    if len(twaccount_db.error) !=0 : continue
    # Not the first time, and not it is not time to follow  
    if (twaccount_db.specifiedfavoritelastfavorite != None) and (datetime.datetime.utcfromtimestamp(time.time()) < datetime.timedelta(minutes=twaccount_db.specifiedfavoritetweetduration) + twaccount_db.specifiedfavoritelastfavorite): continue   
    options = TaskRetryOptions(task_retry_limit=0,task_age_limit=1)
    if util.run_on_backend():
      deferred.defer(autofavoritetweettask,twaccount_db.key,_countdown=random.randint(0,60),_retry_options=options,_target='backend-jobs')
    else:
      deferred.defer(autofavoritetweettask,twaccount_db.key,_countdown=random.randint(0,60),_retry_options=options)    
  return 'Done'

```


```
def autofavoritetweettask(twaccount_db_key):
  twaccount_db = twaccount_db_key.get()
  tweet_db = model.SpecifiedFavorite.query().filter(ndb.GenericProperty('twaccount_key') == twaccount_db.key).filter(ndb.GenericProperty('favorited') == False).get()
  if tweet_db:        
    twauth = tweepy.OAuthHandler(twaccount_db.twitter_consumer_key,
                                  twaccount_db.twitter_consumer_secret)
    twauth.set_access_token(twaccount_db.access_token_key, twaccount_db.access_token_secret)
    api = tweepy.API(twauth)
    try:
      api.create_favorite(int(tweet_db.tweetid))
    except tweepy.TweepError, e:
      if e.message[0]['code'] == 139: #[{u'message': u'You have already favorited this status.', u'code': 139}]
        pass
      else:
        util.tweepyerrorhandle(twaccount_db,e)
        tweet_db.key.delete()
        return 'Task failed'
    tweet_db.favoriteat = datetime.datetime.utcfromtimestamp(time.time())
    tweet_db.favorited = True
    tweet_db.put()  

    
    twaccount_db.specifiedfavoritelastfavorite = datetime.datetime.utcfromtimestamp(time.time())
    twaccount_db.put()
  return 'Finished task successfully'
```

**Comment by gmist** [comment]
[Limitations of the deferred library](https://cloud.google.com/appengine/articles/deferred?csw=1#limitations-of-the-deferred-library)

```
You can't pass a method defined in the request handler module
```

**Comment by do-n-khanh** [comment]
hi gmist,

i have read about that before. I have tried to move the function autofavoritetweettask into a new py file, and then import in in request handle module file. However, it does not solve the problem
